export const RAW_RECIPES = `abeille = animal sauvage+fleur
acier = charbon+métal
aigle = montagne+oiseau
aiguille = fil+métal ou foin+métal
aile de poulet = os+poulet
air = air est un des éléments fondamentales.
alcool = fruit+temps ou jus+temps
algue = mer+plante ou océan+plante
algues = eau+plante ou mer+plante ou océan+plante
allergie = humain+poussière
alligator = lézard+marais ou lézard+rivière
alpaga = montagne+mouton
ambulance = docteur+voiture ou hôpital+voiture
amour = 2 ×humain
ampoule = électricité+verre
ange = humain+oiseau
anguille électrique = électricité+poisson
animal sauvage = forêt+vie
anneau = diamant+métal ou diamant+or
antarctique = désert+glace ou désert+neige
aquarium = eau+verre ou poisson+verre
araignée = animal sauvage+fil
arbre de noël = ampoule+arbre ou arbre+étoile
arbre fruitier = arbre+fruit
arbre généalogique = arbre+famille
arbre = plante+temps
arc en ciel = lumière+pluie ou pluie+soleil
archipel = 2 ×île
argent = or+papier
argile = boue+sable
armure = acier+outil ou métal+outil
aspirateur = balai+électricité
Astronaut ice cream = astronaute+crème glacée
astronaute = espace+humain ou fusée+humain ou humain+Lune ou humain+station spatiale
atmosphère = air+pression ou ciel+pression
âtre = brique+feu de camp ou feu de camp+maison ou feu de camp+mur
aurore = antarctique+atmosphère ou antarctique+ciel ou antarctique+soleil
autruche = oiseau+sable ou oiseau+terre
avalanche = énergie+neige
avion en papier = avion+papier
avion = acier+oiseau ou métal+oiseau
bactéries = marais+vie
baguette magique = bois+magicien
baïonnette = épée+pistolet ou lame+pistolet
balai = bois+foin
balle = métal+poudre à canon
banane = fruit+singe
bandage = sang+tissu
banque = argent+maison ou coffre-fort+maison ou maison+or
barbe à papa = électricité+sucre ou nuage+sucre
barrage = arbre+castor ou bois+castor ou castor+rivière ou mur+rivière
bas de noël = âtre+laine
bateau à voile = bateau+tissu ou bateau+vent
bateau pirate = bateau à voile+pirate ou bateau+pirate
bateau = bois+eau
Batman = chauve-souris+humain
bbq = feu de camp+jardin ou feu de camp+viande
beignet = huile+pâte
bétail = animal sauvage+fermier ou animal sauvage+humain ou fermier+vie
beurre = énergie+lait ou lait+pression
bibliothèque = livre+maison
bière = alcool+blé
biscuit chinois = gâteau+papier
blé = champ+fermier ou fermier+plante
blizzard = neige+tempête ou neige+vent ou 2 ×neige
bois = arbre+outil
bombe atomique = énergie+explosion
bonhomme de neige = boule de neige+carotte ou carotte+neige ou humain+neige ou 2 ×boule de neige
bonhomme de pain d'épices = pâte+vie
bonsaï = arbre+ciseaux ou arbre+poterie
botte de foin = 2 ×foin
boucher = humain+viande
boue = eau+terre
bougie = cire+feu ou cire+fil
boulanger = farine+humain ou humain+pain ou humain+pâte
boulangerie = boulanger+maison ou maison+pain
boule de cristal = magicien+verre ou sorcière+verre
boule de neige = humain+neige
brique = argile+feu ou argile+soleil ou boue+feu ou boue+soleil
brouillard = nuage+terre
bûcheron = hache+humain ou humain+tronçonneuse
bulle de savon = air+savon ou eau+savon
bus = 2 ×voiture
cabane dans les arbres = arbre+maison
cabane = bois+maison
cachemire = chèvre de montagne+ciseaux ou chèvre de montagne+fil ou chèvre de montagne+laine ou chèvre de montagne+outil ou chèvre de montagne+tissu
cactus = désert+plante ou plante+sable
cadavre = faucheuse+humain ou humain+pistolet
Cadbury Eggs = chocolat+œuf
cadeau = arbre de noël+Père Noël ou âtre+Père Noël ou bas de noël+Père Noël ou cheminée+Père Noël ou gâteau+Père Noël
cadran solaire = horloge+soleil
caméléon = arc en ciel+lézard
camion de crème glacée = crème glacée+voiture
camion de pompier = pompier+voiture
canard = caneton+temps ou eau+oiseau ou étang+oiseau ou lac+oiseau
caneton = canard+œuf
canne à pêche = bois+poisson ou outil+poisson
canne à sucre = arbre de noël+sucre
canon = bateau pirate+poudre à canon ou château+poudre à canon
cape = héros+tissu
Caramel Apple = caramel+verger
caramel = feu+sucre
Caramelo = caramel+chocolat
caravane = maison+voiture
carotte = bonhomme de neige+légume ou bonhomme de neige+soleil
carte au trésor = carte+pirate
carte = papier+terre
cascade = montagne+rivière
castor = animal sauvage+barrage ou animal sauvage+bois
caviar = humain+œufs de poisson
cellule solaire = outil+soleil
cendre = énergie+volcan
centaure = cheval+humain
cercueil = bois+cadavre
céréales = blé+lait
cerf-volant = ciel+papier ou papier+vent
chaîne de montagnes = 2 ×montagne
chaîne = acier+corde ou corde+métal
chameau = animal sauvage+désert ou bétail+désert ou cheval+désert
champ = fermier+terre ou outil+terre
charbon de bois = arbre+feu ou bois+feu
charbon = bonhomme de neige+soleil ou plante+pression
chariot = bois+roue
chat de clavier = chat+musique
chat = animal sauvage+lait
château de sable = château+sable
château = chevalier+maison
chaudière = métal+vapeur
chaudron = acier+sorcière ou âtre+sorcière ou feu de camp+sorcière ou métal+sorcière
chauve-souris = ciel+souris ou oiseau+souris
cheeseburger = fromage+hamburger
cheminée = âtre+brique ou âtre+maison ou brique+fumée
Cheval de Troie = bois+cheval
cheval = bétail+foin
chevalier = armure+humain
chèvre de montagne = chaîne de montagnes+chèvre ou chèvre+montagne
chèvre = bétail+montagne
chien = animal sauvage+humain ou loup+os
chocolat = rivière+Willy Wonka
ciel = air+nuage
cigarette = papier+tabac
cimetière = 2 ×pierre tombale ou 2 ×tombe
cire = abeille+ruche
ciseaux = 2 ×lame
citrouille d'halloween = bougie+citrouille ou citrouille+feu ou citrouille+lame
citrouille = feu+légume ou légume+lumière
clôture = bois+mur
cochon = bétail+boue
coffre-fort = acier+argent ou acier+or ou argent+métal ou métal+or
colibri = fleur+oiseau
confettis = ciseaux+papier ou lame+papier
confiture = jus+sucre
constellation = 2 ×étoile
conte de fées = château+histoire ou chevalier+histoire ou dragon+histoire ou histoire+monarque
corbeau = champ+oiseau ou épouvantail+oiseau
corde = 2 ×fil
coton = nuage+plante
coucou = horloge+oiseau
couronne = métal+monarque ou monarque+or
crayon (mine de plomb) = bois+charbon de bois ou bois+charbon
crayon = arc en ciel+cire ou arc en ciel+crayon (mine de plomb)
crème glacée = froid+lait ou glace+lait
crépuscule = jour+nuit
cuir = cochon+lame ou lame+vache
cyborg = humain+robot
cycliste = humain+vélo
Darth Vader = feu+Jedi ou Jedi+lave
désert = cactus+sable ou 2 ×sable
diamant = charbon+pression ou charbon+temps
dinosaure = lézard+temps
dioxyde de carbone = arbre+nuit ou humain+oxygène ou nuit+plante
docteur = hôpital+humain
Doge = chien+Internet ou chien+ordinateur
Don Quichotte = chevalier+moulin à vent
double arc en ciel! = 2 ×arc en ciel
dragon = feu+lézard
drone = avion+robot
dune = désert+vent ou plage+vent ou sable+vent
dynamite = fil électrique+poudre à canon
eau = feu+glace ou eau est un des éléments fondamentales.
éclipse = Lune+soleil
écureuil volant = avion+écureuil ou ciel+écureuil ou écureuil+oiseau ou écureuil+vent
écureuil = arbre+souris
électricien = électricité+humain ou fil électrique+humain
électricité = cellule solaire+lumière ou cellule solaire+soleil ou énergie+métal ou éolienne+vent
email = Internet+lettre ou lettre+ordinateur
énergie = air+feu ou plante+soleil
éolienne = électricité+moulin à vent
épée = acier+lame ou lame+métal
épouvantail = foin+humain
éruption = énergie+volcan
espace = ciel+étoile ou étoile+Lune ou étoile+soleil
espadon = épée+poisson
étang = eau+jardin
étoile de mer = étoile+mer ou étoile+océan ou étoile+poisson
étoile = ciel+nuit ou nuit+télescope
excalibur = épée+pierre
explosion = feu+poudre à canon
extincteur = dioxyde de carbone+feu ou dioxyde de carbone+métal ou dioxyde de carbone+pression
extraterrestre = espace+vie
facteur = humain+lettre
famille = humain+maison
fantôme = château+nuit ou cimetière+nuit
farine = blé+moulin à vent ou blé+pierre ou blé+roue à aubes
faucheuse = cadavre+faux ou faux+humain
faune = chèvre+humain
faux = blé+lame ou herbe-grass+lame
fenêtre = maison+verre
fer à cheval = cheval+métal
ferme = fermier+grange ou fermier+maison
fermier = champ+humain ou fourche+humain ou humain+plante
feu d'artifice = ciel+explosion
feu de camp = bois+feu
feu = feu est un des éléments fondamentales.
feuille = arbre+vent
fibre optique = fil électrique+lumière
fil électrique = électricité+métal
fil = coton+outil ou laine+roue
flaque = bonhomme de neige+lance-flammes ou bonhomme de neige+soleil ou glace+soleil
fleur = jardin+plante
flûte = bois+vent
foin = faux+herbe-grass ou fermier+herbe-grass ou herbe-grass+soleil
fontaine = eau+statue
forêt = 2 ×arbre
fossile = dinosaure+pierre ou dinosaure+temps ou dinosaure+terre
fourche = foin+outil
fourmi = animal sauvage+herbe-grass ou animal sauvage+sucre
Frankenstein = cadavre+électricité ou électricité+zombie
frigo = électricité+froid ou froid+métal ou glace+métal
frites = huile+légume
froid = humain+pluie
fromage grillé = fromage+toast
fromage = lait+temps
fruit = arbre+fermier ou arbre+soleil
fumée = bois+feu
Fun Dip = sable+sucre
fusée = avion+espace
galaxie = 2 ×étoile
gâteau (tarte) = bougie+pâte
gâteau = pâte+sucre
geyser = terre+vapeur
gilet pare-balles = armure+balle
glace = eau+froid
glacier = glace+montagne
globe de neige = arbre de noël+verre ou bonhomme de neige+verre ou boule de cristal+neige ou neige+verre
gnome = jardin+statue
Godzilla = dinosaure+ville
goldfish = fromage+poisson
golem = argile+vie
grange = bétail+maison ou foin+maison ou maison+vache
granit = lave+pression
gratte-ciel = ciel+maison
grêle = glace+nuage ou glace+pluie ou glace+tempête
grenade = explosion+métal
grenouille = animal sauvage+étang
grès = pierre+sable
guerrier = épée+humain
guimauves = feu de camp+sucre
Guinness Float = bière+crème glacée
hache = bois+lame
haie = clôture+feuille ou clôture+plante
hamburger = pain+viande
hamster = roue+souris
harpe = ange+musique
hélicoptère = avion+lame ou avion+moulin à vent
herbe à chat = chat+plante
herbe-grass = plante+terre
herbe = feuille+maladie ou maladie+plante
héros = chevalier+dragon
hibou = magicien+oiseau ou nuit+oiseau
hippocampe = cheval+mer ou cheval+océan ou cheval+poisson
hippopotame = cheval+eau ou cheval+rivière
histoire = feu de camp+humain
hôpital = ambulance+maison ou docteur+maison ou maison+maladie
horizon = ciel+mer ou ciel+océan ou ciel+terre
horloge = électricité+temps ou outil+temps ou roue+temps
huile = pression+tournesol
humain = terre+vie
hydravion = avion+eau ou avion+mer ou avion+océan
iceberg = antarctique+mer ou antarctique+océan ou glace+mer ou glace+océan
idée = ampoule+humain ou ampoule+nerd
iglou = glace+maison ou maison+neige
île = mer+volcan ou océan+volcan
imprimante = ordinateur+papier
ingénieur = humain+outil
inondation = pluie+temps ou 2 ×pluie
Internet = fil électrique+ordinateur ou ordinateur+toile ou 2 ×ordinateur
ivre = alcool+humain ou bière+humain ou humain+vin
jambon = fumée+viande
jardin = herbe-grass+maison ou herbe-grass+plante ou 2 ×fleur ou 2 ×plante
jardinier = humain+jardin
Jedi = chevalier+sabre laser ou humain+sabre laser
jour = ciel+soleil ou nuit+soleil ou nuit+temps ou soleil+temps
journal = 2 ×papier
Juicy Fruit = fruit+jus
jus = eau+fruit ou fruit+pression
lac = barrage+rivière ou eau+étang
laine = ciseaux+mouton ou mouton+outil
lait au chocolat = chocolat+lait
lait de coco = lait+noix de coco ou noix de coco+outil
lait = fermier+vache ou humain+vache
lamantin = mer+vache
lame = métal+pierre
lampe à huile = argile+huile ou corde+huile ou feu+huile ou huile+poterie ou huile+verre
lampe à lave = lampe+lave
lampe de poche = lumière+outil
lampe = ampoule+métal
lance-flammes = feu+pistolet
lapin = animal sauvage+carotte
lard = cochon+feu
lasso = cheval+corde ou corde+vache
lave = feu+terre
le docteur = docteur+tardis
légume = champ+fruit
lettre = crayon (mine de plomb)+papier
lézard = marais+œuf
licorne = arc en ciel+cheval ou arc en ciel+vie ou cheval+double arc en ciel! ou double arc en ciel!+vie
lierre = mur+plante
limonade = eau+fruit
lion = animal sauvage+chat
livre de recettes = livre+recette ou 2 ×recette
livre = bois+papier ou histoire+papier
loup-garou = humain+loup-garou ou humain+loup
loup = animal sauvage+chien ou animal sauvage+Lune ou chien+forêt
lumière = ampoule+électricité ou électricité+lampe de poche
Lune = ciel+fromage ou ciel+pierre
lunettes de natation = eau+lunettes
lunettes de protection = explosion+lunettes ou ingénieur+lunettes ou lunettes+outil
lunettes de ski = lunettes+neige
lunettes de soleil = lunettes+plage ou lunettes+soleil
lunettes = métal+verre ou 2 ×verre
machine à coudre = aiguille+électricité ou aiguille+robot
magicien = énergie+humain
maison en pain d'épice = bonhomme de pain d'épices+maison ou maison+pâte
maison = bois+humain ou brique+humain ou brique+outil ou 2 ×mur
mal de mer = bateau à voile+maladie ou bateau+maladie ou maladie+mer ou maladie+navire à vapeur ou maladie+océan
maladie = bactéries+humain ou humain+maladie ou humain+pluie
marais = boue+herbe-grass ou boue+plante
marée = Lune+mer ou Lune+océan
marin = bateau à voile+humain ou bateau+humain
Mars = planète+rouille
marteau = bois+métal
mayonnaise = huile+œuf
méduse = humain+serpent
mer = 2 ×eau
métal = feu+pierre
météore = atmosphère+météorite ou ciel+météorite
météorite = espace+pierre
microscope = bactéries+lunettes ou bactéries+verre
miel = abeille+fleur ou abeille+ruche
milk-shake = crème glacée+lait
Milky Way = espace+lait
minotaure = humain+vache
minuteur = horloge+œuf ou montre+œuf
miroir = métal+verre
mixeur = électricité+lame ou lame+verre
moisissure = pain+temps
momie = cadavre+pyramide
monarque = château+humain ou couronne+humain ou excalibur+humain
montagne = terre+tremblement de terre
montagnes russes = chariot+montagne ou montagne+train
montre = horloge+humain
moteur à vapeur = chaudière+outil ou chaudière+roue
moto = acier+vélo ou énergie+vélo
motoneige = moto+neige ou neige+voiture
mouette = mer+oiseau ou océan+oiseau ou oiseau+plage
moulin à vent = maison+vent ou roue+vent
Mounds = chocolat+noix de coco
mousse = algues+pierre ou pierre+plante
mouton = bétail+nuage
mur = 2 ×brique
musique = flûte+humain ou humain+son
nageur = humain+lunettes de natation
narguilé = eau+pipe
narval = eau+licorne ou licorne+mer ou licorne+océan
navire à vapeur = bateau+moteur à vapeur ou eau+moteur à vapeur
neige carbonique = dioxyde de carbone+froid ou dioxyde de carbone+glace
neige = froid+pluie ou froid+vapeur
nénuphar = étang+fleur
nerd = humain+lunettes
Nerds = nerd+sucre
Nessie = histoire+lac
niche = chien+maison
nichoir = maison+oiseau
nid = arbre+oiseau ou foin+œuf ou foin+oiseau
ninja = humain+shuriken
noix de coco = fruit+palmier
noix = arbre+écureuil
nuage = air+vapeur
nuit = ciel+Lune ou jour+temps ou Lune+temps
oasis = arbre+désert ou désert+eau ou désert+palmier
obsidienne = eau+lave
océan = eau+mer ou 2 ×mer
œuf = pierre+vie ou 2 ×lézard ou 2 ×oiseau ou 2 ×tortue
œufs de poisson = eau+œuf ou étang+œuf ou mer+œuf ou océan+œuf ou 2 ×poisson
oiseau = air+œuf ou air+vie ou ciel+œuf ou ciel+vie
omelette = feu+œuf
or = arc en ciel+métal ou métal+soleil
ordinateur = électricité+nerd ou fil électrique+nerd ou nerd+outil
oreiller = coton+tissu
origami = oiseau+papier
ornithorynque = canard+castor
os = cadavre+temps
ouragan = énergie+vent
outil = humain+métal
ovni = avion+extraterrestre ou extraterrestre+fusée
oxygène = dioxyde de carbone+plante ou plante+soleil
ozone = électricité+oxygène ou 2 ×oxygène
paille de fer = acier+laine ou fil électrique+laine
pain à la banane = banane+pain
pain = feu+pâte
palmier = arbre+île ou arbre+plage
paon = arc en ciel+oiseau
papier d'emballage = cadeau+papier
papier de verre = papier+sable
papier = bois+pression
papillon de nuit = Lune+papillon ou nuit+papillon
papillon = animal sauvage+fleur
parachute = parapluie+pilote ou pilote+tissu
parapluie = outil+pluie ou pluie+tissu
paresseux = animal sauvage+temps
parfum = alcool+fleur ou alcool+rose ou eau+fleur ou eau+rose ou fleur+vapeur ou rose+vapeur
partition = musique+papier
pâte à biscuits = gâteau+pâte
pâte à gâteau = farine+lait
pâte = eau+farine
pâtes au fromage = fromage+pâtes
pâtes = farine+œuf
pêcheur = canne à pêche+humain
Peeps = poulet+sucre
pégase = cheval+ciel ou cheval+oiseau ou licorne+oiseau
peinture = arc en ciel+eau ou crayon (mine de plomb)+eau
pénicilline = docteur+moisissure
Père Noël = arbre de noël+humain
perroquet = oiseau+pirate
pétrole = fossile+pression ou fossile+temps
phare = lumière+maison ou lumière+mer ou lumière+océan ou lumière+plage
phénix = feu+oiseau
phoque = chien+mer
piège à souris = bois+fromage ou fromage+métal
pierre tombale = pierre+tombe
pierre = air+lave
pigeon = lettre+oiseau ou oiseau+statue ou oiseau+ville
pilote = avion+humain ou humain+hydravion
pingouin = animal sauvage+glace ou glace+oiseau ou neige+oiseau
pinocchio = bois+vie
pipe = bois+tabac
pique-nique = herbe-grass+sandwich ou plage+sandwich
piranha = poisson+sang
pirate = bateau pirate+marin ou épée+marin
pistolet à eau = eau+pistolet
pistolet = balle+métal
pivert = bois+oiseau
pizza = fromage+pâte
plage = eau+sable ou mer+sable ou océan+sable
plan = ingénieur+papier
plancton = eau+vie ou mer+vie ou océan+vie
planète = espace+terre
plante = pluie+terre
pluie acide = fumée+pluie ou pluie+smog
pluie = air+eau ou eau+nuage
poisson-frites = frites+poisson
poisson volant = ciel+poisson ou oiseau+poisson
poisson = œufs de poisson+temps
Pokki = écureuil+ordinateur
pompier = camion de pompier+humain ou feu+humain
pont = acier+rivière ou bois+rivière ou métal+rivière
Pop Rocks = explosion+pierre
portefeuille = argent+cuir
poterie = argile+feu ou argile+outil ou argile+roue
poudre à canon = feu+poussière
poulet = bétail+œuf ou bétail+oiseau ou fermier+oiseau
poussière = air+terre ou jour+vampire ou soleil+vampire
pression = 2 ×air ou 2 ×terre
prisme = arc en ciel+verre
Ptérodactyle = air+dinosaure ou dinosaure+oiseau
pull = humain+laine ou laine+outil
pyramide = désert+pierre ou désert+tombe
rat = animal sauvage+bateau à voile ou animal sauvage+bateau pirate
rauque = chien+glace ou chien+neige
rayon x = lumière+os ou lumière+squelette
recette = boulanger+papier ou farine+papier
Red Vines = fil électrique+sucre
règle = bois+crayon (mine de plomb)
renard = animal sauvage+poulet
renne = animal sauvage+Père Noël ou bétail+Père Noël
requin = animal sauvage+mer ou animal sauvage+océan ou mer+sang ou océan+sang
réveil = horloge+son
Ring Pop = diamant+sucre
rivière = eau+montagne ou montagne+pluie
robot = acier+vie ou armure+vie ou métal+vie
roomba = aspirateur+robot
rose = amour+fleur ou amour+plante
rosée = brouillard+herbe-grass ou eau+herbe-grass
roue à aubes = eau+roue ou rivière+roue
roue = bois+outil
rouille = acier+air ou acier+oxygène ou air+métal ou métal+oxygène
ruche = abeille+arbre ou abeille+maison
ruines = château+temps ou maison+temps
sable = air+pierre ou pierre+vent
sables mouvants = marais+sable
sablier = sable+verre
sabre laser = électricité+épée ou énergie+épée ou épée+lumière
sandwich = fromage+pain ou jambon+pain ou lard+pain
sang = humain+lame
sanglier = animal sauvage+cochon ou cochon+forêt
saturne = anneau+planète
savon = cendre+huile
scalpel = docteur+lame ou hôpital+lame
scorpion = animal sauvage+dune ou animal sauvage+sable
sel = feu+mer ou feu+océan ou mer+soleil ou océan+soleil
selle = cheval+cuir
serpent = animal sauvage+fil électrique
serre = plante+verre ou 2 ×fenêtre
shuriken = étoile+lame
signal de fumée = feu de camp+tissu ou fumée+tissu
singe = animal sauvage+arbre
sirène = humain+poisson
skateboard = roue+snowboard
Skittles = arc en ciel+sucre
smog = brouillard+fumée ou brouillard+ville
smoothie = fruit+mixeur
snowboard = bois+neige ou neige+surfeur
soda = dioxyde de carbone+eau ou dioxyde de carbone+jus
soleil = ciel+feu
son = air+vague
sorcière = balai+humain ou balai+magicien
soupe de poulet = eau+poulet
souris d'ordinateur = ordinateur+souris
souris = animal sauvage+fromage
spaghetti = fil+pâtes
sphinx = humain+lion
squelette = cadavre+temps ou 2 ×os
Starburst = fruit+fusée
station spatiale = espace+maison
statue = humain+méduse ou outil+pierre
steak = bbq+viande ou feu+vache
stéthoscope = docteur+outil
sucette glacée = froid+jus ou glace+jus
sucre = énergie+fruit ou énergie+jus ou feu+jus
super nova = étoile+explosion
surfeur = humain+vague
sushi = algue+caviar ou algue+poisson
Swedish Fish = poisson+sucre
Sweethearts = amour+sucre
système solaire = planète+soleil
tabac = feu+plante
taille-crayon = crayon (mine de plomb)+lame
tambour = bois+cuir
tank = armure+voiture ou pistolet+voiture
tardis = espace+temps
tarte = fruit+pâte
taser = électricité+pistolet
tatou = animal sauvage+armure
télescope = ciel+verre ou espace+verre ou étoile+verre
tempête de sable = énergie+sable ou ouragan+sable ou sable+tempête
tempête = électricité+nuage ou énergie+nuage
temps = sable+verre
tente = bois+tissu ou maison+tissu
terre = terre est un des éléments fondamentales.
thé glacé = froid+thé ou glace+thé
thé = eau+feuille
tirelire = argent+cochon ou cochon+poterie
tissu = fil+outil
titanic = iceberg+navire à vapeur
toast = feu+pain ou feu+sandwich
toile = araignée+fil
tombe = cadavre+terre ou cercueil+terre
tondeuse à gazon = électricité+faux ou herbe-grass+outil
Tortue Ninja = ninja+tortue
tortue = œuf+sable
toucan = arc en ciel+oiseau
tournesol = fleur+soleil ou plante+soleil
tracteur = champ+voiture ou fermier+voiture
train = acier+moteur à vapeur ou métal+moteur à vapeur ou moteur à vapeur+roue ou moteur à vapeur+wagon
traîneau = chariot+neige ou neige+wagon
tremblement de terre = énergie+terre ou terre+vague
trésor = carte au trésor+pirate
tronçonneuse = électricité+hache
trou noir = étoile+pression
tsunami = mer+tremblement de terre ou océan+tremblement de terre
tunnel = ingénieur+montagne
Twix = Caramelo+gâteau
tyrannosaurus rex = dinosaure+viande
une bague = anneau+volcan
vache = bétail+herbe-grass
vague = mer+vent ou océan+vent
vaisseau spatial = astronaute+avion
vampire = humain+sang ou humain+vampire
vapeur = eau+énergie ou eau+feu
vase = fleur+poterie ou plante+poterie
vautour = cadavre+oiseau
vélo = 2 ×roue
vent = air+énergie ou air+pression
verger = arbre fruitier+champ ou 2 ×arbre fruitier
vermicelles = confettis+sucre
verre = électricité+sable ou feu+sable
viande séchée = sel+viande ou soleil+viande
viande = bétail+boucher ou bétail+lame ou boucher+cochon ou boucher+vache ou cochon+outil ou outil+vache
vie = amour+temps ou énergie+marais
village = 2 ×maison
ville = 2 ×gratte-ciel ou 2 ×village
vin = alcool+fruit
vinaigre = air+vin ou oxygène+vin ou temps+vin
voiture électrique = électricité+voiture
voiture = métal+roue
volcan = feu+montagne ou lave+montagne ou lave+terre
wagon = chariot+cheval
Willy Wonka = ingénieur+sucre
yack = montagne+vache
yaourt = bactéries+lait
yéti = chaîne de montagnes+histoire ou histoire+montagne
Yoda = Jedi+marais
yogourt glacé = froid+yaourt ou glace+yaourt
zombie = cadavre+vie ou humain+zombie`
