-- Insert all recipes using element IDs
-- This script converts all recipes from the game data into database entries

INSERT INTO recipes (ingredient1_id, ingredient2_id, result_id) VALUES
-- Base combinations
((SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'vapeur')),
((SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'boue')),
((SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'lave')),
((SELECT element_id FROM elements WHERE name = 'air'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'pluie')),
((SELECT element_id FROM elements WHERE name = 'air'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'énergie')),
((SELECT element_id FROM elements WHERE name = 'air'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'poussière')),

-- Extended recipes (parsing from game data)
((SELECT element_id FROM elements WHERE name = 'animal sauvage'), (SELECT element_id FROM elements WHERE name = 'fleur'), (SELECT element_id FROM elements WHERE name = 'abeille')),
((SELECT element_id FROM elements WHERE name = 'abeille'), (SELECT element_id FROM elements WHERE name = 'oiseau'), (SELECT element_id FROM elements WHERE name = 'colibri')),
((SELECT element_id FROM elements WHERE name = 'abeille'), (SELECT element_id FROM elements WHERE name = 'ruche'), (SELECT element_id FROM elements WHERE name = 'miel')),
((SELECT element_id FROM elements WHERE name = 'acide'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'rouille')),
((SELECT element_id FROM elements WHERE name = 'acier'), (SELECT element_id FROM elements WHERE name = 'électricité'), (SELECT element_id FROM elements WHERE name = 'robot')),
((SELECT element_id FROM elements WHERE name = 'air'), (SELECT element_id FROM elements WHERE name = 'glace'), (SELECT element_id FROM elements WHERE name = 'grêle')),
((SELECT element_id FROM elements WHERE name = 'air'), (SELECT element_id FROM elements WHERE name = 'lave'), (SELECT element_id FROM elements WHERE name = 'pierre')),
((SELECT element_id FROM elements WHERE name = 'air'), (SELECT element_id FROM elements WHERE name = 'vapeur'), (SELECT element_id FROM elements WHERE name = 'nuage')),
((SELECT element_id FROM elements WHERE name = 'algue'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'varech')),
((SELECT element_id FROM elements WHERE name = 'alligator'), (SELECT element_id FROM elements WHERE name = 'marais'), (SELECT element_id FROM elements WHERE name = 'reptile')),
((SELECT element_id FROM elements WHERE name = 'alpaga'), (SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'lama')),
((SELECT element_id FROM elements WHERE name = 'ambulance'), (SELECT element_id FROM elements WHERE name = 'hôpital'), (SELECT element_id FROM elements WHERE name = 'urgence')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'arc-en-ciel'), (SELECT element_id FROM elements WHERE name = 'licorne')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'désert'), (SELECT element_id FROM elements WHERE name = 'chameau')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'poisson')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'forêt'), (SELECT element_id FROM elements WHERE name = 'cerf')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'homme'), (SELECT element_id FROM elements WHERE name = 'élevage')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'chèvre de montagne')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'scorpion')),
((SELECT element_id FROM elements WHERE name = 'animal'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'ver de terre')),
((SELECT element_id FROM elements WHERE name = 'animal sauvage'), (SELECT element_id FROM elements WHERE name = 'homme'), (SELECT element_id FROM elements WHERE name = 'domestication')),
((SELECT element_id FROM elements WHERE name = 'arbre'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'cendre')),
((SELECT element_id FROM elements WHERE name = 'arbre'), (SELECT element_id FROM elements WHERE name = 'fruit'), (SELECT element_id FROM elements WHERE name = 'verger')),
((SELECT element_id FROM elements WHERE name = 'arbre'), (SELECT element_id FROM elements WHERE name = 'hache'), (SELECT element_id FROM elements WHERE name = 'bois')),
((SELECT element_id FROM elements WHERE name = 'arbre'), (SELECT element_id FROM elements WHERE name = 'neige'), (SELECT element_id FROM elements WHERE name = 'sapin')),
((SELECT element_id FROM elements WHERE name = 'arbre'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'forêt')),
((SELECT element_id FROM elements WHERE name = 'arc'), (SELECT element_id FROM elements WHERE name = 'flèche'), (SELECT element_id FROM elements WHERE name = 'arc et flèches')),
((SELECT element_id FROM elements WHERE name = 'arc-en-ciel'), (SELECT element_id FROM elements WHERE name = 'pluie'), (SELECT element_id FROM elements WHERE name = 'prisme')),
((SELECT element_id FROM elements WHERE name = 'araignée'), (SELECT element_id FROM elements WHERE name = 'toile'), (SELECT element_id FROM elements WHERE name = 'piège')),
((SELECT element_id FROM elements WHERE name = 'argile'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'brique')),
((SELECT element_id FROM elements WHERE name = 'argile'), (SELECT element_id FROM elements WHERE name = 'homme'), (SELECT element_id FROM elements WHERE name = 'poterie')),
((SELECT element_id FROM elements WHERE name = 'atmosphère'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'nuage')),
((SELECT element_id FROM elements WHERE name = 'atome'), (SELECT element_id FROM elements WHERE name = 'atome'), (SELECT element_id FROM elements WHERE name = 'molécule')),
((SELECT element_id FROM elements WHERE name = 'avion'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'avion de chasse')),
((SELECT element_id FROM elements WHERE name = 'bactérie'), (SELECT element_id FROM elements WHERE name = 'lait'), (SELECT element_id FROM elements WHERE name = 'yaourt')),
((SELECT element_id FROM elements WHERE name = 'bactérie'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'évolution')),
((SELECT element_id FROM elements WHERE name = 'baleine'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'cétacé')),
((SELECT element_id FROM elements WHERE name = 'bambou'), (SELECT element_id FROM elements WHERE name = 'panda'), (SELECT element_id FROM elements WHERE name = 'nourriture')),
((SELECT element_id FROM elements WHERE name = 'barrage'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'hydroélectricité')),
((SELECT element_id FROM elements WHERE name = 'bateau'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'navigation')),
((SELECT element_id FROM elements WHERE name = 'bateau'), (SELECT element_id FROM elements WHERE name = 'pirate'), (SELECT element_id FROM elements WHERE name = 'navire pirate')),
((SELECT element_id FROM elements WHERE name = 'bateau'), (SELECT element_id FROM elements WHERE name = 'voile'), (SELECT element_id FROM elements WHERE name = 'voilier')),
((SELECT element_id FROM elements WHERE name = 'bière'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'fermentation')),
((SELECT element_id FROM elements WHERE name = 'bijou'), (SELECT element_id FROM elements WHERE name = 'or'), (SELECT element_id FROM elements WHERE name = 'bague')),
((SELECT element_id FROM elements WHERE name = 'biscuit'), (SELECT element_id FROM elements WHERE name = 'chocolat'), (SELECT element_id FROM elements WHERE name = 'cookie')),
((SELECT element_id FROM elements WHERE name = 'blé'), (SELECT element_id FROM elements WHERE name = 'moulin'), (SELECT element_id FROM elements WHERE name = 'farine')),
((SELECT element_id FROM elements WHERE name = 'bois'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'charbon')),
((SELECT element_id FROM elements WHERE name = 'bois'), (SELECT element_id FROM elements WHERE name = 'lame'), (SELECT element_id FROM elements WHERE name = 'épée en bois')),
((SELECT element_id FROM elements WHERE name = 'bois'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'outil')),
((SELECT element_id FROM elements WHERE name = 'bombe'), (SELECT element_id FROM elements WHERE name = 'explosion'), (SELECT element_id FROM elements WHERE name = 'destruction')),
((SELECT element_id FROM elements WHERE name = 'boue'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'brique')),
((SELECT element_id FROM elements WHERE name = 'boue'), (SELECT element_id FROM elements WHERE name = 'plante'), (SELECT element_id FROM elements WHERE name = 'marais')),
((SELECT element_id FROM elements WHERE name = 'boue'), (SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'argile')),
((SELECT element_id FROM elements WHERE name = 'bougie'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'lumière')),
((SELECT element_id FROM elements WHERE name = 'brouillard'), (SELECT element_id FROM elements WHERE name = 'ville'), (SELECT element_id FROM elements WHERE name = 'smog')),
((SELECT element_id FROM elements WHERE name = 'cactus'), (SELECT element_id FROM elements WHERE name = 'désert'), (SELECT element_id FROM elements WHERE name = 'plante du désert')),
((SELECT element_id FROM elements WHERE name = 'café'), (SELECT element_id FROM elements WHERE name = 'eau chaude'), (SELECT element_id FROM elements WHERE name = 'boisson')),
((SELECT element_id FROM elements WHERE name = 'canne à sucre'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'sucre')),
((SELECT element_id FROM elements WHERE name = 'caramel'), (SELECT element_id FROM elements WHERE name = 'chocolat'), (SELECT element_id FROM elements WHERE name = 'confiserie')),
((SELECT element_id FROM elements WHERE name = 'carbone'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'diamant')),
((SELECT element_id FROM elements WHERE name = 'carte'), (SELECT element_id FROM elements WHERE name = 'papier'), (SELECT element_id FROM elements WHERE name = 'jeu de cartes')),
((SELECT element_id FROM elements WHERE name = 'castor'), (SELECT element_id FROM elements WHERE name = 'rivière'), (SELECT element_id FROM elements WHERE name = 'barrage')),
((SELECT element_id FROM elements WHERE name = 'cave'), (SELECT element_id FROM elements WHERE name = 'vin'), (SELECT element_id FROM elements WHERE name = 'vieillissement')),
((SELECT element_id FROM elements WHERE name = 'cendre'), (SELECT element_id FROM elements WHERE name = 'verre'), (SELECT element_id FROM elements WHERE name = 'vitre')),
((SELECT element_id FROM elements WHERE name = 'cerveau'), (SELECT element_id FROM elements WHERE name = 'électricité'), (SELECT element_id FROM elements WHERE name = 'pensée')),
((SELECT element_id FROM elements WHERE name = 'chaîne'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'chaîne en métal')),
((SELECT element_id FROM elements WHERE name = 'chaleur'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'fusion')),
((SELECT element_id FROM elements WHERE name = 'chameau'), (SELECT element_id FROM elements WHERE name = 'désert'), (SELECT element_id FROM elements WHERE name = 'caravane')),
((SELECT element_id FROM elements WHERE name = 'champ'), (SELECT element_id FROM elements WHERE name = 'graine'), (SELECT element_id FROM elements WHERE name = 'récolte')),
((SELECT element_id FROM elements WHERE name = 'charbon'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'énergie')),
((SELECT element_id FROM elements WHERE name = 'charbon'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'diamant')),
((SELECT element_id FROM elements WHERE name = 'chat'), (SELECT element_id FROM elements WHERE name = 'lait'), (SELECT element_id FROM elements WHERE name = 'chaton')),
((SELECT element_id FROM elements WHERE name = 'château'), (SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'forteresse')),
((SELECT element_id FROM elements WHERE name = 'cheval'), (SELECT element_id FROM elements WHERE name = 'homme'), (SELECT element_id FROM elements WHERE name = 'cavalier')),
((SELECT element_id FROM elements WHERE name = 'cheval'), (SELECT element_id FROM elements WHERE name = 'selle'), (SELECT element_id FROM elements WHERE name = 'monture')),
((SELECT element_id FROM elements WHERE name = 'chien'), (SELECT element_id FROM elements WHERE name = 'neige'), (SELECT element_id FROM elements WHERE name = 'husky')),
((SELECT element_id FROM elements WHERE name = 'chocolat'), (SELECT element_id FROM elements WHERE name = 'lait'), (SELECT element_id FROM elements WHERE name = 'chocolat au lait')),
((SELECT element_id FROM elements WHERE name = 'ciel'), (SELECT element_id FROM elements WHERE name = 'oiseau'), (SELECT element_id FROM elements WHERE name = 'vol')),
((SELECT element_id FROM elements WHERE name = 'ciel'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'pluie')),
((SELECT element_id FROM elements WHERE name = 'ciment'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'béton')),
((SELECT element_id FROM elements WHERE name = 'citrouille'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'jack o'' lantern')),
((SELECT element_id FROM elements WHERE name = 'cire'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'bougie')),
((SELECT element_id FROM elements WHERE name = 'cocotier'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'noix de coco')),
((SELECT element_id FROM elements WHERE name = 'confettis'), (SELECT element_id FROM elements WHERE name = 'fête'), (SELECT element_id FROM elements WHERE name = 'célébration')),
((SELECT element_id FROM elements WHERE name = 'continent'), (SELECT element_id FROM elements WHERE name = 'continent'), (SELECT element_id FROM elements WHERE name = 'terre')),
((SELECT element_id FROM elements WHERE name = 'corail'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'récif')),
((SELECT element_id FROM elements WHERE name = 'corps'), (SELECT element_id FROM elements WHERE name = 'esprit'), (SELECT element_id FROM elements WHERE name = 'âme')),
((SELECT element_id FROM elements WHERE name = 'courant'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'électricité')),
((SELECT element_id FROM elements WHERE name = 'cristal'), (SELECT element_id FROM elements WHERE name = 'lumière'), (SELECT element_id FROM elements WHERE name = 'prisme')),
((SELECT element_id FROM elements WHERE name = 'cuir'), (SELECT element_id FROM elements WHERE name = 'fil'), (SELECT element_id FROM elements WHERE name = 'sac')),
((SELECT element_id FROM elements WHERE name = 'cuivre'), (SELECT element_id FROM elements WHERE name = 'électricité'), (SELECT element_id FROM elements WHERE name = 'fil électrique')),
((SELECT element_id FROM elements WHERE name = 'cyclone'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'ouragan')),
((SELECT element_id FROM elements WHERE name = 'désert'), (SELECT element_id FROM elements WHERE name = 'plante'), (SELECT element_id FROM elements WHERE name = 'cactus')),
((SELECT element_id FROM elements WHERE name = 'désert'), (SELECT element_id FROM elements WHERE name = 'tempête'), (SELECT element_id FROM elements WHERE name = 'tempête de sable')),
((SELECT element_id FROM elements WHERE name = 'dinosaure'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'fossile')),
((SELECT element_id FROM elements WHERE name = 'drapeau'), (SELECT element_id FROM elements WHERE name = 'pays'), (SELECT element_id FROM elements WHERE name = 'nation')),
((SELECT element_id FROM elements WHERE name = 'dune'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'désert')),
((SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'froid'), (SELECT element_id FROM elements WHERE name = 'glace')),
((SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'glace'), (SELECT element_id FROM elements WHERE name = 'eau')),
((SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'lac'), (SELECT element_id FROM elements WHERE name = 'étang')),
((SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'plante'), (SELECT element_id FROM elements WHERE name = 'algue')),
((SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'vague')),
((SELECT element_id FROM elements WHERE name = 'éclair'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'électricité')),
((SELECT element_id FROM elements WHERE name = 'éclair'), (SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'verre')),
((SELECT element_id FROM elements WHERE name = 'éclipse'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'ombre')),
((SELECT element_id FROM elements WHERE name = 'électricité'), (SELECT element_id FROM elements WHERE name = 'poisson'), (SELECT element_id FROM elements WHERE name = 'anguille électrique')),
((SELECT element_id FROM elements WHERE name = 'électricité'), (SELECT element_id FROM elements WHERE name = 'verre'), (SELECT element_id FROM elements WHERE name = 'ampoule')),
((SELECT element_id FROM elements WHERE name = 'énergie'), (SELECT element_id FROM elements WHERE name = 'marais'), (SELECT element_id FROM elements WHERE name = 'gaz des marais')),
((SELECT element_id FROM elements WHERE name = 'énergie'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'électricité')),
((SELECT element_id FROM elements WHERE name = 'énergie'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'solaire')),
((SELECT element_id FROM elements WHERE name = 'épée'), (SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'excalibur')),
((SELECT element_id FROM elements WHERE name = 'espace'), (SELECT element_id FROM elements WHERE name = 'étoile'), (SELECT element_id FROM elements WHERE name = 'galaxie')),
((SELECT element_id FROM elements WHERE name = 'espace'), (SELECT element_id FROM elements WHERE name = 'vaisseau'), (SELECT element_id FROM elements WHERE name = 'astronaute')),
((SELECT element_id FROM elements WHERE name = 'essence'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'explosion')),
((SELECT element_id FROM elements WHERE name = 'étoile'), (SELECT element_id FROM elements WHERE name = 'nuit'), (SELECT element_id FROM elements WHERE name = 'constellation')),
((SELECT element_id FROM elements WHERE name = 'explosion'), (SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'volcan')),
((SELECT element_id FROM elements WHERE name = 'farine'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'pâte')),
((SELECT element_id FROM elements WHERE name = 'fer'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'acier')),
((SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'métal')),
((SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'verre')),
((SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'fumée')),
((SELECT element_id FROM elements WHERE name = 'feu d''artifice'), (SELECT element_id FROM elements WHERE name = 'nuit'), (SELECT element_id FROM elements WHERE name = 'spectacle')),
((SELECT element_id FROM elements WHERE name = 'feuille'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'arbre')),
((SELECT element_id FROM elements WHERE name = 'feuille'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'tourbillon')),
((SELECT element_id FROM elements WHERE name = 'fil'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'câble')),
((SELECT element_id FROM elements WHERE name = 'fleur'), (SELECT element_id FROM elements WHERE name = 'jardin'), (SELECT element_id FROM elements WHERE name = 'bouquet')),
((SELECT element_id FROM elements WHERE name = 'fleur'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'pollen')),
((SELECT element_id FROM elements WHERE name = 'fleuve'), (SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'source')),
((SELECT element_id FROM elements WHERE name = 'forêt'), (SELECT element_id FROM elements WHERE name = 'pluie'), (SELECT element_id FROM elements WHERE name = 'forêt tropicale')),
((SELECT element_id FROM elements WHERE name = 'forêt'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'jungle')),
((SELECT element_id FROM elements WHERE name = 'fossile'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'pétrole')),
((SELECT element_id FROM elements WHERE name = 'four'), (SELECT element_id FROM elements WHERE name = 'pâte'), (SELECT element_id FROM elements WHERE name = 'pain')),
((SELECT element_id FROM elements WHERE name = 'froid'), (SELECT element_id FROM elements WHERE name = 'pluie'), (SELECT element_id FROM elements WHERE name = 'neige')),
((SELECT element_id FROM elements WHERE name = 'fromage'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'fromage affiné')),
((SELECT element_id FROM elements WHERE name = 'fruit'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'fruit mûr')),
((SELECT element_id FROM elements WHERE name = 'fruit'), (SELECT element_id FROM elements WHERE name = 'sucre'), (SELECT element_id FROM elements WHERE name = 'confiture')),
((SELECT element_id FROM elements WHERE name = 'fumée'), (SELECT element_id FROM elements WHERE name = 'signal'), (SELECT element_id FROM elements WHERE name = 'signal de fumée')),
((SELECT element_id FROM elements WHERE name = 'fusée'), (SELECT element_id FROM elements WHERE name = 'étoile'), (SELECT element_id FROM elements WHERE name = 'voyage spatial')),
((SELECT element_id FROM elements WHERE name = 'galaxie'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'univers')),
((SELECT element_id FROM elements WHERE name = 'gaz'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'explosion')),
((SELECT element_id FROM elements WHERE name = 'geyser'), (SELECT element_id FROM elements WHERE name = 'vapeur'), (SELECT element_id FROM elements WHERE name = 'eau chaude')),
((SELECT element_id FROM elements WHERE name = 'glace'), (SELECT element_id FROM elements WHERE name = 'lait'), (SELECT element_id FROM elements WHERE name = 'glace (dessert)')),
((SELECT element_id FROM elements WHERE name = 'glace'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'iceberg')),
((SELECT element_id FROM elements WHERE name = 'glace'), (SELECT element_id FROM elements WHERE name = 'sel'), (SELECT element_id FROM elements WHERE name = 'eau salée gelée')),
((SELECT element_id FROM elements WHERE name = 'glacier'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'fonte')),
((SELECT element_id FROM elements WHERE name = 'granit'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'marbre')),
((SELECT element_id FROM elements WHERE name = 'graine'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'plante')),
((SELECT element_id FROM elements WHERE name = 'graine'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'arbre')),
((SELECT element_id FROM elements WHERE name = 'grotte'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'stalactite')),
((SELECT element_id FROM elements WHERE name = 'guitare'), (SELECT element_id FROM elements WHERE name = 'son'), (SELECT element_id FROM elements WHERE name = 'musique')),
((SELECT element_id FROM elements WHERE name = 'hache'), (SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'hache de pierre')),
((SELECT element_id FROM elements WHERE name = 'herbe'), (SELECT element_id FROM elements WHERE name = 'vache'), (SELECT element_id FROM elements WHERE name = 'pâturage')),
((SELECT element_id FROM elements WHERE name = 'herbe'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'foin')),
((SELECT element_id FROM elements WHERE name = 'hiver'), (SELECT element_id FROM elements WHERE name = 'arbre'), (SELECT element_id FROM elements WHERE name = 'sapin')),
((SELECT element_id FROM elements WHERE name = 'homme'), (SELECT element_id FROM elements WHERE name = 'outil'), (SELECT element_id FROM elements WHERE name = 'artisan')),
((SELECT element_id FROM elements WHERE name = 'homme'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'civilisation')),
((SELECT element_id FROM elements WHERE name = 'horloge'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'chronomètre')),
((SELECT element_id FROM elements WHERE name = 'huile'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'essence')),
((SELECT element_id FROM elements WHERE name = 'humain'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'cyborg')),
((SELECT element_id FROM elements WHERE name = 'humain'), (SELECT element_id FROM elements WHERE name = 'oiseau'), (SELECT element_id FROM elements WHERE name = 'ange')),
((SELECT element_id FROM elements WHERE name = 'idée'), (SELECT element_id FROM elements WHERE name = 'papier'), (SELECT element_id FROM elements WHERE name = 'livre')),
((SELECT element_id FROM elements WHERE name = 'île'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'archipel')),
((SELECT element_id FROM elements WHERE name = 'île'), (SELECT element_id FROM elements WHERE name = 'volcan'), (SELECT element_id FROM elements WHERE name = 'île volcanique')),
((SELECT element_id FROM elements WHERE name = 'insecte'), (SELECT element_id FROM elements WHERE name = 'lumière'), (SELECT element_id FROM elements WHERE name = 'luciole')),
((SELECT element_id FROM elements WHERE name = 'jardin'), (SELECT element_id FROM elements WHERE name = 'statue'), (SELECT element_id FROM elements WHERE name = 'jardin zen')),
((SELECT element_id FROM elements WHERE name = 'jardin'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'verger')),
((SELECT element_id FROM elements WHERE name = 'jus'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'vin')),
((SELECT element_id FROM elements WHERE name = 'lac'), (SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'lac de montagne')),
((SELECT element_id FROM elements WHERE name = 'laine'), (SELECT element_id FROM elements WHERE name = 'outil'), (SELECT element_id FROM elements WHERE name = 'tissu')),
((SELECT element_id FROM elements WHERE name = 'lait'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'beurre')),
((SELECT element_id FROM elements WHERE name = 'lait'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'fromage')),
((SELECT element_id FROM elements WHERE name = 'lame'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'épée')),
((SELECT element_id FROM elements WHERE name = 'lampe'), (SELECT element_id FROM elements WHERE name = 'lumière'), (SELECT element_id FROM elements WHERE name = 'lampe de poche')),
((SELECT element_id FROM elements WHERE name = 'lave'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'pierre ponce')),
((SELECT element_id FROM elements WHERE name = 'lave'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'obsidienne')),
((SELECT element_id FROM elements WHERE name = 'lettre'), (SELECT element_id FROM elements WHERE name = 'papier'), (SELECT element_id FROM elements WHERE name = 'message')),
((SELECT element_id FROM elements WHERE name = 'levure'), (SELECT element_id FROM elements WHERE name = 'pâte'), (SELECT element_id FROM elements WHERE name = 'pain')),
((SELECT element_id FROM elements WHERE name = 'lézard'), (SELECT element_id FROM elements WHERE name = 'marais'), (SELECT element_id FROM elements WHERE name = 'crocodile')),
((SELECT element_id FROM elements WHERE name = 'lierre'), (SELECT element_id FROM elements WHERE name = 'mur'), (SELECT element_id FROM elements WHERE name = 'mur végétal')),
((SELECT element_id FROM elements WHERE name = 'livre'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'bibliothèque')),
((SELECT element_id FROM elements WHERE name = 'loup'), (SELECT element_id FROM elements WHERE name = 'lune'), (SELECT element_id FROM elements WHERE name = 'loup-garou')),
((SELECT element_id FROM elements WHERE name = 'lumière'), (SELECT element_id FROM elements WHERE name = 'prisme'), (SELECT element_id FROM elements WHERE name = 'arc-en-ciel')),
((SELECT element_id FROM elements WHERE name = 'lune'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'éclipse')),
((SELECT element_id FROM elements WHERE name = 'lune'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'marée')),
((SELECT element_id FROM elements WHERE name = 'magma'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'volcan')),
((SELECT element_id FROM elements WHERE name = 'maison'), (SELECT element_id FROM elements WHERE name = 'neige'), (SELECT element_id FROM elements WHERE name = 'igloo')),
((SELECT element_id FROM elements WHERE name = 'maïs'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'pop-corn')),
((SELECT element_id FROM elements WHERE name = 'marais'), (SELECT element_id FROM elements WHERE name = 'reptile'), (SELECT element_id FROM elements WHERE name = 'crocodile')),
((SELECT element_id FROM elements WHERE name = 'marteau'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'forge')),
((SELECT element_id FROM elements WHERE name = 'mer'), (SELECT element_id FROM elements WHERE name = 'sel'), (SELECT element_id FROM elements WHERE name = 'eau salée')),
((SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'outil'), (SELECT element_id FROM elements WHERE name = 'machine')),
((SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'roue'), (SELECT element_id FROM elements WHERE name = 'voiture')),
((SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'son'), (SELECT element_id FROM elements WHERE name = 'cloche')),
((SELECT element_id FROM elements WHERE name = 'météorite'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'cratère')),
((SELECT element_id FROM elements WHERE name = 'miroir'), (SELECT element_id FROM elements WHERE name = 'lumière'), (SELECT element_id FROM elements WHERE name = 'reflet')),
((SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'neige'), (SELECT element_id FROM elements WHERE name = 'sommet enneigé')),
((SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'érosion')),
((SELECT element_id FROM elements WHERE name = 'montagne'), (SELECT element_id FROM elements WHERE name = 'volcan'), (SELECT element_id FROM elements WHERE name = 'mont volcanique')),
((SELECT element_id FROM elements WHERE name = 'moulin'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'moulin à vent')),
((SELECT element_id FROM elements WHERE name = 'mouton'), (SELECT element_id FROM elements WHERE name = 'outil'), (SELECT element_id FROM elements WHERE name = 'laine')),
((SELECT element_id FROM elements WHERE name = 'moustique'), (SELECT element_id FROM elements WHERE name = 'sang'), (SELECT element_id FROM elements WHERE name = 'piqûre')),
((SELECT element_id FROM elements WHERE name = 'mousse'), (SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'lichen')),
((SELECT element_id FROM elements WHERE name = 'mur'), (SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'fortification')),
((SELECT element_id FROM elements WHERE name = 'nage'), (SELECT element_id FROM elements WHERE name = 'poisson'), (SELECT element_id FROM elements WHERE name = 'sirène')),
((SELECT element_id FROM elements WHERE name = 'neige'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'blizzard')),
((SELECT element_id FROM elements WHERE name = 'nid'), (SELECT element_id FROM elements WHERE name = 'oiseau'), (SELECT element_id FROM elements WHERE name = 'œuf')),
((SELECT element_id FROM elements WHERE name = 'nuage'), (SELECT element_id FROM elements WHERE name = 'électricité'), (SELECT element_id FROM elements WHERE name = 'orage')),
((SELECT element_id FROM elements WHERE name = 'nuage'), (SELECT element_id FROM elements WHERE name = 'froid'), (SELECT element_id FROM elements WHERE name = 'neige')),
((SELECT element_id FROM elements WHERE name = 'nuit'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'jour')),
((SELECT element_id FROM elements WHERE name = 'observatoire'), (SELECT element_id FROM elements WHERE name = 'télescope'), (SELECT element_id FROM elements WHERE name = 'astronomie')),
((SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'sel'), (SELECT element_id FROM elements WHERE name = 'eau salée')),
((SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'marée')),
((SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'tsunami')),
((SELECT element_id FROM elements WHERE name = 'œuf'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'poussin')),
((SELECT element_id FROM elements WHERE name = 'oiseau'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'œuf')),
((SELECT element_id FROM elements WHERE name = 'or'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'métal précieux')),
((SELECT element_id FROM elements WHERE name = 'orage'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'tempête')),
((SELECT element_id FROM elements WHERE name = 'ours'), (SELECT element_id FROM elements WHERE name = 'glace'), (SELECT element_id FROM elements WHERE name = 'ours polaire')),
((SELECT element_id FROM elements WHERE name = 'oxygène'), (SELECT element_id FROM elements WHERE name = 'plante'), (SELECT element_id FROM elements WHERE name = 'photosynthèse')),
((SELECT element_id FROM elements WHERE name = 'pain'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'pain rassis')),
((SELECT element_id FROM elements WHERE name = 'palmier'), (SELECT element_id FROM elements WHERE name = 'plage'), (SELECT element_id FROM elements WHERE name = 'cocotier')),
((SELECT element_id FROM elements WHERE name = 'papier'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'cerf-volant')),
((SELECT element_id FROM elements WHERE name = 'papillon'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'métamorphose')),
((SELECT element_id FROM elements WHERE name = 'parfum'), (SELECT element_id FROM elements WHERE name = 'fleur'), (SELECT element_id FROM elements WHERE name = 'essence florale')),
((SELECT element_id FROM elements WHERE name = 'pâte'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'pain')),
((SELECT element_id FROM elements WHERE name = 'peinture'), (SELECT element_id FROM elements WHERE name = 'toile'), (SELECT element_id FROM elements WHERE name = 'tableau')),
((SELECT element_id FROM elements WHERE name = 'pétale'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'fleur')),
((SELECT element_id FROM elements WHERE name = 'pétrole'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'essence')),
((SELECT element_id FROM elements WHERE name = 'phare'), (SELECT element_id FROM elements WHERE name = 'lumière'), (SELECT element_id FROM elements WHERE name = 'signal')),
((SELECT element_id FROM elements WHERE name = 'philosophie'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'sagesse')),
((SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'diamant')),
((SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'sable')),
((SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'vie'), (SELECT element_id FROM elements WHERE name = 'golem')),
((SELECT element_id FROM elements WHERE name = 'pigeon'), (SELECT element_id FROM elements WHERE name = 'lettre'), (SELECT element_id FROM elements WHERE name = 'pigeon voyageur')),
((SELECT element_id FROM elements WHERE name = 'pilote'), (SELECT element_id FROM elements WHERE name = 'avion'), (SELECT element_id FROM elements WHERE name = 'aviation')),
((SELECT element_id FROM elements WHERE name = 'pirate'), (SELECT element_id FROM elements WHERE name = 'trésor'), (SELECT element_id FROM elements WHERE name = 'carte au trésor')),
((SELECT element_id FROM elements WHERE name = 'plage'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'vague')),
((SELECT element_id FROM elements WHERE name = 'planète'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'système solaire')),
((SELECT element_id FROM elements WHERE name = 'plante'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'photosynthèse')),
((SELECT element_id FROM elements WHERE name = 'plante'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'arbre')),
((SELECT element_id FROM elements WHERE name = 'plume'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'vol')),
((SELECT element_id FROM elements WHERE name = 'pluie'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'arc-en-ciel')),
((SELECT element_id FROM elements WHERE name = 'pluie'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'boue')),
((SELECT element_id FROM elements WHERE name = 'poisson'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'fossile')),
((SELECT element_id FROM elements WHERE name = 'pollen'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'allergie')),
((SELECT element_id FROM elements WHERE name = 'pomme'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'cidre')),
((SELECT element_id FROM elements WHERE name = 'pont'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'passage')),
((SELECT element_id FROM elements WHERE name = 'pot'), (SELECT element_id FROM elements WHERE name = 'plante'), (SELECT element_id FROM elements WHERE name = 'pot de fleur')),
((SELECT element_id FROM elements WHERE name = 'poule'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'œuf')),
((SELECT element_id FROM elements WHERE name = 'poussière'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'cendre')),
((SELECT element_id FROM elements WHERE name = 'poussière'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'tempête de sable')),
((SELECT element_id FROM elements WHERE name = 'pression'), (SELECT element_id FROM elements WHERE name = 'vapeur'), (SELECT element_id FROM elements WHERE name = 'moteur à vapeur')),
((SELECT element_id FROM elements WHERE name = 'prisme'), (SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'spectre')),
((SELECT element_id FROM elements WHERE name = 'raisin'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'vin')),
((SELECT element_id FROM elements WHERE name = 'requin'), (SELECT element_id FROM elements WHERE name = 'océan'), (SELECT element_id FROM elements WHERE name = 'prédateur')),
((SELECT element_id FROM elements WHERE name = 'rivière'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'canyon')),
((SELECT element_id FROM elements WHERE name = 'riz'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'rizière')),
((SELECT element_id FROM elements WHERE name = 'robot'), (SELECT element_id FROM elements WHERE name = 'vie'), (SELECT element_id FROM elements WHERE name = 'intelligence artificielle')),
((SELECT element_id FROM elements WHERE name = 'roche'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'érosion')),
((SELECT element_id FROM elements WHERE name = 'roue'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'chariot')),
((SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'dune')),
((SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'verre'), (SELECT element_id FROM elements WHERE name = 'sablier')),
((SELECT element_id FROM elements WHERE name = 'saison'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'année')),
((SELECT element_id FROM elements WHERE name = 'savon'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'bulle')),
((SELECT element_id FROM elements WHERE name = 'science'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'découverte')),
((SELECT element_id FROM elements WHERE name = 'semence'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'plante')),
((SELECT element_id FROM elements WHERE name = 'serpent'), (SELECT element_id FROM elements WHERE name = 'venin'), (SELECT element_id FROM elements WHERE name = 'cobra')),
((SELECT element_id FROM elements WHERE name = 'sirop'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'caramel')),
((SELECT element_id FROM elements WHERE name = 'sol'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'fossile')),
((SELECT element_id FROM elements WHERE name = 'soleil'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'jour')),
((SELECT element_id FROM elements WHERE name = 'son'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'écho')),
((SELECT element_id FROM elements WHERE name = 'soufre'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'acide')),
((SELECT element_id FROM elements WHERE name = 'source'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'rivière')),
((SELECT element_id FROM elements WHERE name = 'statue'), (SELECT element_id FROM elements WHERE name = 'pierre'), (SELECT element_id FROM elements WHERE name = 'sculpture')),
((SELECT element_id FROM elements WHERE name = 'sucre'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'caramel')),
((SELECT element_id FROM elements WHERE name = 'sueur'), (SELECT element_id FROM elements WHERE name = 'sel'), (SELECT element_id FROM elements WHERE name = 'eau salée')),
((SELECT element_id FROM elements WHERE name = 'surf'), (SELECT element_id FROM elements WHERE name = 'vague'), (SELECT element_id FROM elements WHERE name = 'sport nautique')),
((SELECT element_id FROM elements WHERE name = 'table'), (SELECT element_id FROM elements WHERE name = 'nourriture'), (SELECT element_id FROM elements WHERE name = 'repas')),
((SELECT element_id FROM elements WHERE name = 'telescope'), (SELECT element_id FROM elements WHERE name = 'étoile'), (SELECT element_id FROM elements WHERE name = 'observation')),
((SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'vie'), (SELECT element_id FROM elements WHERE name = 'mort')),
((SELECT element_id FROM elements WHERE name = 'tempête'), (SELECT element_id FROM elements WHERE name = 'mer'), (SELECT element_id FROM elements WHERE name = 'ouragan')),
((SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'feu'), (SELECT element_id FROM elements WHERE name = 'lave')),
((SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'graine'), (SELECT element_id FROM elements WHERE name = 'plante')),
((SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'vie'), (SELECT element_id FROM elements WHERE name = 'golem')),
((SELECT element_id FROM elements WHERE name = 'thé'), (SELECT element_id FROM elements WHERE name = 'froid'), (SELECT element_id FROM elements WHERE name = 'thé glacé')),
((SELECT element_id FROM elements WHERE name = 'tissu'), (SELECT element_id FROM elements WHERE name = 'fil'), (SELECT element_id FROM elements WHERE name = 'vêtement')),
((SELECT element_id FROM elements WHERE name = 'toile'), (SELECT element_id FROM elements WHERE name = 'araignée'), (SELECT element_id FROM elements WHERE name = 'toile d''araignée')),
((SELECT element_id FROM elements WHERE name = 'toit'), (SELECT element_id FROM elements WHERE name = 'neige'), (SELECT element_id FROM elements WHERE name = 'avalanche')),
((SELECT element_id FROM elements WHERE name = 'tornade'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'cyclone')),
((SELECT element_id FROM elements WHERE name = 'tortue'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'longévité')),
((SELECT element_id FROM elements WHERE name = 'train'), (SELECT element_id FROM elements WHERE name = 'vapeur'), (SELECT element_id FROM elements WHERE name = 'locomotive')),
((SELECT element_id FROM elements WHERE name = 'trésor'), (SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'trésor enfoui')),
((SELECT element_id FROM elements WHERE name = 'tsunami'), (SELECT element_id FROM elements WHERE name = 'ville'), (SELECT element_id FROM elements WHERE name = 'catastrophe')),
((SELECT element_id FROM elements WHERE name = 'uranium'), (SELECT element_id FROM elements WHERE name = 'énergie'), (SELECT element_id FROM elements WHERE name = 'nucléaire')),
((SELECT element_id FROM elements WHERE name = 'vache'), (SELECT element_id FROM elements WHERE name = 'pré'), (SELECT element_id FROM elements WHERE name = 'élevage')),
((SELECT element_id FROM elements WHERE name = 'vague'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'surf')),
((SELECT element_id FROM elements WHERE name = 'vapeur'), (SELECT element_id FROM elements WHERE name = 'métal'), (SELECT element_id FROM elements WHERE name = 'machine à vapeur')),
((SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'tempête de sable')),
((SELECT element_id FROM elements WHERE name = 'ver'), (SELECT element_id FROM elements WHERE name = 'terre'), (SELECT element_id FROM elements WHERE name = 'ver de terre')),
((SELECT element_id FROM elements WHERE name = 'verre'), (SELECT element_id FROM elements WHERE name = 'sable'), (SELECT element_id FROM elements WHERE name = 'vitre')),
((SELECT element_id FROM elements WHERE name = 'vie'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'évolution')),
((SELECT element_id FROM elements WHERE name = 'vie'), (SELECT element_id FROM elements WHERE name = 'eau'), (SELECT element_id FROM elements WHERE name = 'algue')),
((SELECT element_id FROM elements WHERE name = 'ville'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'métropole')),
((SELECT element_id FROM elements WHERE name = 'vin'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'vinaigre')),
((SELECT element_id FROM elements WHERE name = 'vinaigre'), (SELECT element_id FROM elements WHERE name = 'bicarbonate'), (SELECT element_id FROM elements WHERE name = 'réaction chimique')),
((SELECT element_id FROM elements WHERE name = 'voile'), (SELECT element_id FROM elements WHERE name = 'vent'), (SELECT element_id FROM elements WHERE name = 'navigation')),
((SELECT element_id FROM elements WHERE name = 'voiture'), (SELECT element_id FROM elements WHERE name = 'route'), (SELECT element_id FROM elements WHERE name = 'circulation')),
((SELECT element_id FROM elements WHERE name = 'volcan'), (SELECT element_id FROM elements WHERE name = 'temps'), (SELECT element_id FROM elements WHERE name = 'montagne')),
((SELECT element_id FROM elements WHERE name = 'zombie'), (SELECT element_id FROM elements WHERE name = 'humain'), (SELECT element_id FROM elements WHERE name = 'apocalypse'));
