-- Insert ALL recipes into the recipes table
-- This script uses a temporary table and INNER JOINs to ensure all elements exist
-- Recipes with missing elements are automatically skipped

-- Create temporary table with all raw recipe data
CREATE TEMP TABLE temp_recipes (
  ingredient1 TEXT,
  ingredient2 TEXT,
  result TEXT
);

-- Insert all recipe combinations
INSERT INTO temp_recipes (ingredient1, ingredient2, result) VALUES
('animal sauvage', 'fleur', 'abeille'),
('charbon', 'métal', 'acier'),
('montagne', 'oiseau', 'aigle'),
('fil', 'métal', 'aiguille'),
('foin', 'métal', 'aiguille'),
('os', 'poulet', 'aile de poulet'),
('fruit', 'temps', 'alcool'),
('jus', 'temps', 'alcool'),
('mer', 'plante', 'algue'),
('océan', 'plante', 'algue'),
('eau', 'plante', 'algues'),
('mer', 'plante', 'algues'),
('océan', 'plante', 'algues'),
('humain', 'poussière', 'allergie'),
('lézard', 'marais', 'alligator'),
('lézard', 'rivière', 'alligator'),
('montagne', 'mouton', 'alpaga'),
('docteur', 'voiture', 'ambulance'),
('hôpital', 'voiture', 'ambulance'),
('humain', 'humain', 'amour'),
('électricité', 'verre', 'ampoule'),
('humain', 'oiseau', 'ange'),
('électricité', 'poisson', 'anguille électrique'),
('forêt', 'vie', 'animal sauvage'),
('diamant', 'métal', 'anneau'),
('diamant', 'or', 'anneau'),
('désert', 'glace', 'antarctique'),
('désert', 'neige', 'antarctique'),
('eau', 'verre', 'aquarium'),
('poisson', 'verre', 'aquarium'),
('animal sauvage', 'fil', 'araignée'),
('ampoule', 'arbre', 'arbre de noël'),
('arbre', 'étoile', 'arbre de noël'),
('arbre', 'fruit', 'arbre fruitier'),
('arbre', 'famille', 'arbre généalogique'),
('plante', 'temps', 'arbre'),
('lumière', 'pluie', 'arc en ciel'),
('pluie', 'soleil', 'arc en ciel'),
('île', 'île', 'archipel'),
('or', 'papier', 'argent'),
('boue', 'sable', 'argile'),
('acier', 'outil', 'armure'),
('métal', 'outil', 'armure'),
('balai', 'électricité', 'aspirateur'),
('astronaute', 'crème glacée', 'Astronaut ice cream'),
('espace', 'humain', 'astronaute'),
('fusée', 'humain', 'astronaute'),
('humain', 'Lune', 'astronaute'),
('humain', 'station spatiale', 'astronaute'),
('air', 'pression', 'atmosphère'),
('ciel', 'pression', 'atmosphère'),
('brique', 'feu de camp', 'âtre'),
('feu de camp', 'maison', 'âtre'),
('feu de camp', 'mur', 'âtre'),
('antarctique', 'atmosphère', 'aurore'),
('antarctique', 'ciel', 'aurore'),
('antarctique', 'soleil', 'aurore'),
('oiseau', 'sable', 'autruche'),
('oiseau', 'terre', 'autruche'),
('énergie', 'neige', 'avalanche'),
('avion', 'papier', 'avion en papier'),
('acier', 'oiseau', 'avion'),
('métal', 'oiseau', 'avion'),
('marais', 'vie', 'bactéries'),
('bois', 'magicien', 'baguette magique'),
('épée', 'pistolet', 'baïonnette'),
('lame', 'pistolet', 'baïonnette'),
('bois', 'foin', 'balai'),
('métal', 'poudre à canon', 'balle'),
('fruit', 'singe', 'banane'),
('sang', 'tissu', 'bandage'),
('argent', 'maison', 'banque'),
('coffre-fort', 'maison', 'banque'),
('maison', 'or', 'banque'),
('électricité', 'sucre', 'barbe à papa'),
('nuage', 'sucre', 'barbe à papa'),
('arbre', 'castor', 'barrage'),
('bois', 'castor', 'barrage'),
('castor', 'rivière', 'barrage'),
('mur', 'rivière', 'barrage'),
('âtre', 'laine', 'bas de noël'),
('bateau', 'tissu', 'bateau à voile'),
('bateau', 'vent', 'bateau à voile'),
('bateau à voile', 'pirate', 'bateau pirate'),
('bateau', 'pirate', 'bateau pirate'),
('bois', 'eau', 'bateau'),
('chauve-souris', 'humain', 'Batman'),
('feu de camp', 'jardin', 'bbq'),
('feu de camp', 'viande', 'bbq'),
('huile', 'pâte', 'beignet'),
('animal sauvage', 'fermier', 'bétail'),
('animal sauvage', 'humain', 'bétail'),
('fermier', 'vie', 'bétail'),
('énergie', 'lait', 'beurre'),
('lait', 'pression', 'beurre'),
('livre', 'maison', 'bibliothèque'),
('alcool', 'blé', 'bière'),
('gâteau', 'papier', 'biscuit chinois'),
('champ', 'fermier', 'blé'),
('fermier', 'plante', 'blé'),
('neige', 'tempête', 'blizzard'),
('neige', 'vent', 'blizzard'),
('neige', 'neige', 'blizzard'),
('arbre', 'outil', 'bois'),
('énergie', 'explosion', 'bombe atomique'),
('boule de neige', 'carotte', 'bonhomme de neige'),
('carotte', 'neige', 'bonhomme de neige'),
('humain', 'neige', 'bonhomme de neige'),
('boule de neige', 'boule de neige', 'bonhomme de neige'),
('pâte', 'vie', 'bonhomme de pain d''épices'),
('arbre', 'ciseaux', 'bonsaï'),
('arbre', 'poterie', 'bonsaï'),
('foin', 'foin', 'botte de foin'),
('humain', 'viande', 'boucher'),
('eau', 'terre', 'boue'),
('cire', 'feu', 'bougie'),
('cire', 'fil', 'bougie'),
('farine', 'humain', 'boulanger'),
('humain', 'pain', 'boulanger'),
('humain', 'pâte', 'boulanger'),
('boulanger', 'maison', 'boulangerie'),
('maison', 'pain', 'boulangerie'),
('magicien', 'verre', 'boule de cristal'),
('sorcière', 'verre', 'boule de cristal'),
('humain', 'neige', 'boule de neige'),
('argile', 'feu', 'brique'),
('argile', 'soleil', 'brique'),
('boue', 'feu', 'brique'),
('boue', 'soleil', 'brique'),
('nuage', 'terre', 'brouillard'),
('hache', 'humain', 'bûcheron'),
('humain', 'tronçonneuse', 'bûcheron'),
('air', 'savon', 'bulle de savon'),
('eau', 'savon', 'bulle de savon'),
('voiture', 'voiture', 'bus'),
('arbre', 'maison', 'cabane dans les arbres'),
('bois', 'maison', 'cabane'),
('chèvre de montagne', 'ciseaux', 'cachemire'),
('chèvre de montagne', 'fil', 'cachemire'),
('chèvre de montagne', 'laine', 'cachemire'),
('chèvre de montagne', 'outil', 'cachemire'),
('chèvre de montagne', 'tissu', 'cachemire'),
('désert', 'plante', 'cactus'),
('plante', 'sable', 'cactus'),
('faucheuse', 'humain', 'cadavre'),
('humain', 'pistolet', 'cadavre'),
('chocolat', 'œuf', 'Cadbury Eggs'),
('arbre de noël', 'Père Noël', 'cadeau'),
('âtre', 'Père Noël', 'cadeau'),
('bas de noël', 'Père Noël', 'cadeau'),
('cheminée', 'Père Noël', 'cadeau'),
('gâteau', 'Père Noël', 'cadeau'),
('horloge', 'soleil', 'cadran solaire'),
('arc en ciel', 'lézard', 'caméléon'),
('crème glacée', 'voiture', 'camion de crème glacée'),
('pompier', 'voiture', 'camion de pompier'),
('caneton', 'temps', 'canard'),
('eau', 'oiseau', 'canard'),
('étang', 'oiseau', 'canard'),
('lac', 'oiseau', 'canard'),
('canard', 'œuf', 'caneton'),
('bois', 'poisson', 'canne à pêche'),
('outil', 'poisson', 'canne à pêche'),
('arbre de noël', 'sucre', 'canne à sucre'),
('bateau pirate', 'poudre à canon', 'canon'),
('château', 'poudre à canon', 'canon'),
('héros', 'tissu', 'cape'),
('caramel', 'verger', 'Caramel Apple'),
('feu', 'sucre', 'caramel'),
('caramel', 'chocolat', 'Caramelo'),
('maison', 'voiture', 'caravane'),
('bonhomme de neige', 'légume', 'carotte'),
('bonhomme de neige', 'soleil', 'carotte'),
('carte', 'pirate', 'carte au trésor'),
('papier', 'terre', 'carte'),
('montagne', 'rivière', 'cascade'),
('animal sauvage', 'barrage', 'castor'),
('animal sauvage', 'bois', 'castor'),
('humain', 'œufs de poisson', 'caviar'),
('outil', 'soleil', 'cellule solaire'),
('énergie', 'volcan', 'cendre'),
('cheval', 'humain', 'centaure'),
('bois', 'cadavre', 'cercueil'),
('blé', 'lait', 'céréales'),
('ciel', 'papier', 'cerf-volant'),
('papier', 'vent', 'cerf-volant'),
('montagne', 'montagne', 'chaîne de montagnes'),
('acier', 'corde', 'chaîne'),
('corde', 'métal', 'chaîne'),
('animal sauvage', 'désert', 'chameau'),
('bétail', 'désert', 'chameau'),
('cheval', 'désert', 'chameau'),
('fermier', 'terre', 'champ'),
('outil', 'terre', 'champ'),
('arbre', 'feu', 'charbon de bois'),
('bois', 'feu', 'charbon de bois'),
('bonhomme de neige', 'soleil', 'charbon'),
('plante', 'pression', 'charbon'),
('bois', 'roue', 'chariot'),
('chat', 'musique', 'chat de clavier'),
('animal sauvage', 'lait', 'chat'),
('château', 'sable', 'château de sable'),
('chevalier', 'maison', 'château'),
('métal', 'vapeur', 'chaudière'),
('acier', 'sorcière', 'chaudron'),
('âtre', 'sorcière', 'chaudron'),
('feu de camp', 'sorcière', 'chaudron'),
('métal', 'sorcière', 'chaudron'),
('ciel', 'souris', 'chauve-souris'),
('oiseau', 'souris', 'chauve-souris'),
('fromage', 'hamburger', 'cheeseburger'),
('âtre', 'brique', 'cheminée'),
('âtre', 'maison', 'cheminée'),
('brique', 'fumée', 'cheminée'),
('bois', 'cheval', 'Cheval de Troie'),
('bétail', 'foin', 'cheval'),
('armure', 'humain', 'chevalier'),
('chaîne de montagnes', 'chèvre', 'chèvre de montagne'),
('chèvre', 'montagne', 'chèvre de montagne'),
('bétail', 'montagne', 'chèvre'),
('animal sauvage', 'humain', 'chien'),
('loup', 'os', 'chien'),
('rivière', 'Willy Wonka', 'chocolat'),
('air', 'nuage', 'ciel'),
('papier', 'tabac', 'cigarette'),
('pierre tombale', 'pierre tombale', 'cimetière'),
('tombe', 'tombe', 'cimetière'),
('abeille', 'ruche', 'cire'),
('lame', 'lame', 'ciseaux'),
('bougie', 'citrouille', 'citrouille d''halloween'),
('citrouille', 'feu', 'citrouille d''halloween'),
('citrouille', 'lame', 'citrouille d''halloween'),
('feu', 'légume', 'citrouille'),
('légume', 'lumière', 'citrouille'),
('bois', 'mur', 'clôture'),
('bétail', 'boue', 'cochon'),
('acier', 'argent', 'coffre-fort'),
('acier', 'or', 'coffre-fort'),
('argent', 'métal', 'coffre-fort'),
('métal', 'or', 'coffre-fort'),
('fleur', 'oiseau', 'colibri'),
('ciseaux', 'papier', 'confettis'),
('lame', 'papier', 'confettis'),
('jus', 'sucre', 'confiture'),
('étoile', 'étoile', 'constellation'),
('château', 'histoire', 'conte de fées'),
('chevalier', 'histoire', 'conte de fées'),
('dragon', 'histoire', 'conte de fées'),
('histoire', 'monarque', 'conte de fées'),
('champ', 'oiseau', 'corbeau'),
('épouvantail', 'oiseau', 'corbeau'),
('fil', 'fil', 'corde'),
('nuage', 'plante', 'coton'),
('horloge', 'oiseau', 'coucou'),
('métal', 'monarque', 'couronne'),
('monarque', 'or', 'couronne'),
('bois', 'charbon de bois', 'crayon (mine de plomb)'),
('bois', 'charbon', 'crayon (mine de plomb)'),
('arc en ciel', 'cire', 'crayon'),
('arc en ciel', 'crayon (mine de plomb)', 'crayon'),
('froid', 'lait', 'crème glacée'),
('glace', 'lait', 'crème glacée'),
('jour', 'nuit', 'crépuscule'),
('cochon', 'lame', 'cuir'),
('lame', 'vache', 'cuir'),
('humain', 'robot', 'cyborg'),
('humain', 'vélo', 'cycliste'),
('feu', 'Jedi', 'Darth Vader'),
('Jedi', 'lave', 'Darth Vader'),
('cactus', 'sable', 'désert'),
('sable', 'sable', 'désert'),
('charbon', 'pression', 'diamant'),
('charbon', 'temps', 'diamant'),
('lézard', 'temps', 'dinosaure'),
('arbre', 'nuit', 'dioxyde de carbone'),
('humain', 'oxygène', 'dioxyde de carbone'),
('nuit', 'plante', 'dioxyde de carbone'),
('hôpital', 'humain', 'docteur'),
('chien', 'Internet', 'Doge'),
('chien', 'ordinateur', 'Doge'),
('chevalier', 'moulin à vent', 'Don Quichotte'),
('arc en ciel', 'arc en ciel', 'double arc en ciel!'),
('feu', 'lézard', 'dragon'),
('avion', 'robot', 'drone'),
('désert', 'vent', 'dune'),
('plage', 'vent', 'dune'),
('sable', 'vent', 'dune'),
('fil électrique', 'poudre à canon', 'dynamite'),
('feu', 'glace', 'eau'),
('Lune', 'soleil', 'éclipse'),
('avion', 'écureuil', 'écureuil volant'),
('ciel', 'écureuil', 'écureuil volant'),
('écureuil', 'oiseau', 'écureuil volant'),
('écureuil', 'vent', 'écureuil volant'),
('arbre', 'souris', 'écureuil'),
('électricité', 'humain', 'électricien'),
('fil électrique', 'humain', 'électricien'),
('cellule solaire', 'lumière', 'électricité'),
('cellule solaire', 'soleil', 'électricité'),
('énergie', 'métal', 'électricité'),
('éolienne', 'vent', 'électricité'),
('Internet', 'lettre', 'email'),
('lettre', 'ordinateur', 'email'),
('air', 'feu', 'énergie'),
('plante', 'soleil', 'énergie'),
('électricité', 'moulin à vent', 'éolienne'),
('acier', 'lame', 'épée'),
('lame', 'métal', 'épée'),
('foin', 'humain', 'épouvantail'),
('énergie', 'volcan', 'éruption'),
('ciel', 'étoile', 'espace'),
('étoile', 'Lune', 'espace'),
('étoile', 'soleil', 'espace'),
('épée', 'poisson', 'espadon'),
('eau', 'jardin', 'étang'),
('étoile', 'mer', 'étoile de mer'),
('étoile', 'océan', 'étoile de mer'),
('étoile', 'poisson', 'étoile de mer'),
('ciel', 'nuit', 'étoile'),
('nuit', 'télescope', 'étoile'),
('épée', 'pierre', 'excalibur'),
('feu', 'poudre à canon', 'explosion'),
('dioxyde de carbone', 'feu', 'extincteur'),
('dioxyde de carbone', 'métal', 'extincteur'),
('dioxyde de carbone', 'pression', 'extincteur'),
('espace', 'vie', 'extraterrestre'),
('humain', 'lettre', 'facteur'),
('humain', 'maison', 'famille'),
('château', 'nuit', 'fantôme'),
('cimetière', 'nuit', 'fantôme'),
('blé', 'moulin à vent', 'farine'),
('blé', 'pierre', 'farine'),
('blé', 'roue à aubes', 'farine'),
('cadavre', 'faux', 'faucheuse'),
('faux', 'humain', 'faucheuse'),
('chèvre', 'humain', 'faune'),
('blé', 'lame', 'faux'),
('herbe-grass', 'lame', 'faux'),
('maison', 'verre', 'fenêtre'),
('cheval', 'métal', 'fer à cheval'),
('fermier', 'grange', 'ferme'),
('fermier', 'maison', 'ferme'),
('champ', 'humain', 'fermier'),
('fourche', 'humain', 'fermier'),
('humain', 'plante', 'fermier'),
('ciel', 'explosion', 'feu d''artifice'),
('bois', 'feu', 'feu de camp'),
('arbre', 'vent', 'feuille'),
('fil électrique', 'lumière', 'fibre optique'),
('électricité', 'métal', 'fil électrique'),
('coton', 'outil', 'fil'),
('laine', 'roue', 'fil'),
('bonhomme de neige', 'lance-flammes', 'flaque'),
('bonhomme de neige', 'soleil', 'flaque'),
('glace', 'soleil', 'flaque'),
('jardin', 'plante', 'fleur'),
('bois', 'vent', 'flûte'),
('faux', 'herbe-grass', 'foin'),
('fermier', 'herbe-grass', 'foin'),
('herbe-grass', 'soleil', 'foin'),
('eau', 'statue', 'fontaine'),
('arbre', 'arbre', 'forêt'),
('dinosaure', 'pierre', 'fossile'),
('dinosaure', 'temps', 'fossile'),
('dinosaure', 'terre', 'fossile'),
('foin', 'outil', 'fourche'),
('animal sauvage', 'herbe-grass', 'fourmi'),
('animal sauvage', 'sucre', 'fourmi'),
('cadavre', 'électricité', 'Frankenstein'),
('électricité', 'zombie', 'Frankenstein'),
('électricité', 'froid', 'frigo'),
('froid', 'métal', 'frigo'),
('glace', 'métal', 'frigo'),
('huile', 'légume', 'frites'),
('humain', 'pluie', 'froid'),
('fromage', 'toast', 'fromage grillé'),
('lait', 'temps', 'fromage'),
('arbre', 'fermier', 'fruit'),
('arbre', 'soleil', 'fruit'),
('bois', 'feu', 'fumée'),
('sable', 'sucre', 'Fun Dip'),
('avion', 'espace', 'fusée'),
('étoile', 'étoile', 'galaxie'),
('bougie', 'pâte', 'gâteau (tarte)'),
('pâte', 'sucre', 'gâteau'),
('terre', 'vapeur', 'geyser'),
('armure', 'balle', 'gilet pare-balles'),
('eau', 'froid', 'glace'),
('glace', 'montagne', 'glacier'),
('arbre de noël', 'verre', 'globe de neige'),
('bonhomme de neige', 'verre', 'globe de neige'),
('boule de cristal', 'neige', 'globe de neige'),
('neige', 'verre', 'globe de neige'),
('jardin', 'statue', 'gnome'),
('dinosaure', 'ville', 'Godzilla'),
('fromage', 'poisson', 'goldfish'),
('argile', 'vie', 'golem'),
('bétail', 'maison', 'grange'),
('foin', 'maison', 'grange'),
('maison', 'vache', 'grange'),
('lave', 'pression', 'granit'),
('ciel', 'maison', 'gratte-ciel'),
('glace', 'nuage', 'grêle'),
('glace', 'pluie', 'grêle'),
('glace', 'tempête', 'grêle'),
('explosion', 'métal', 'grenade'),
('animal sauvage', 'étang', 'grenouille'),
('pierre', 'sable', 'grès'),
('épée', 'humain', 'guerrier'),
('feu de camp', 'sucre', 'guimauves'),
('bière', 'crème glacée', 'Guinness Float'),
('bois', 'lame', 'hache'),
('clôture', 'feuille', 'haie'),
('clôture', 'plante', 'haie'),
('pain', 'viande', 'hamburger'),
('roue', 'souris', 'hamster'),
('ange', 'musique', 'harpe'),
('avion', 'lame', 'hélicoptère'),
('avion', 'moulin à vent', 'hélicoptère'),
('chat', 'plante', 'herbe à chat'),
('plante', 'terre', 'herbe-grass'),
('feuille', 'maladie', 'herbe'),
('maladie', 'plante', 'herbe'),
('chevalier', 'dragon', 'héros'),
('magicien', 'oiseau', 'hibou'),
('nuit', 'oiseau', 'hibou'),
('cheval', 'mer', 'hippocampe'),
('cheval', 'océan', 'hippocampe'),
('cheval', 'poisson', 'hippocampe'),
('cheval', 'eau', 'hippopotame'),
('cheval', 'rivière', 'hippopotame'),
('feu de camp', 'humain', 'histoire'),
('ambulance', 'maison', 'hôpital'),
('docteur', 'maison', 'hôpital'),
('maison', 'maladie', 'hôpital'),
('ciel', 'mer', 'horizon'),
('ciel', 'océan', 'horizon'),
('ciel', 'terre', 'horizon'),
('électricité', 'temps', 'horloge'),
('outil', 'temps', 'horloge'),
('roue', 'temps', 'horloge'),
('pression', 'tournesol', 'huile'),
('terre', 'vie', 'humain'),
('avion', 'eau', 'hydravion'),
('avion', 'mer', 'hydravion'),
('avion', 'océan', 'hydravion'),
('antarctique', 'mer', 'iceberg'),
('antarctique', 'océan', 'iceberg'),
('glace', 'mer', 'iceberg'),
('glace', 'océan', 'iceberg'),
('ampoule', 'humain', 'idée'),
('ampoule', 'nerd', 'idée'),
('glace', 'maison', 'iglou'),
('maison', 'neige', 'iglou'),
('mer', 'volcan', 'île'),
('océan', 'volcan', 'île'),
('ordinateur', 'papier', 'imprimante'),
('humain', 'outil', 'ingénieur'),
('pluie', 'temps', 'inondation'),
('pluie', 'pluie', 'inondation'),
('fil électrique', 'ordinateur', 'Internet'),
('ordinateur', 'toile', 'Internet'),
('ordinateur', 'ordinateur', 'Internet'),
('alcool', 'humain', 'ivre'),
('bière', 'humain', 'ivre'),
('humain', 'vin', 'ivre'),
('fumée', 'viande', 'jambon'),
('herbe-grass', 'maison', 'jardin'),
('herbe-grass', 'plante', 'jardin'),
('fleur', 'fleur', 'jardin'),
('plante', 'plante', 'jardin'),
('humain', 'jardin', 'jardinier'),
('chevalier', 'sabre laser', 'Jedi'),
('humain', 'sabre laser', 'Jedi'),
('ciel', 'soleil', 'jour'),
('nuit', 'soleil', 'jour'),
('nuit', 'temps', 'jour'),
('soleil', 'temps', 'jour'),
('papier', 'papier', 'journal'),
('fruit', 'jus', 'Juicy Fruit'),
('eau', 'fruit', 'jus'),
('fruit', 'pression', 'jus'),
('barrage', 'rivière', 'lac'),
('eau', 'étang', 'lac'),
('ciseaux', 'mouton', 'laine'),
('mouton', 'outil', 'laine'),
('chocolat', 'lait', 'lait au chocolat'),
('lait', 'noix de coco', 'lait de coco'),
('noix de coco', 'outil', 'lait de coco'),
('fermier', 'vache', 'lait'),
('humain', 'vache', 'lait'),
('mer', 'vache', 'lamantin'),
('métal', 'pierre', 'lame'),
('argile', 'huile', 'lampe à huile'),
('corde', 'huile', 'lampe à huile'),
('feu', 'huile', 'lampe à huile'),
('huile', 'poterie', 'lampe à huile'),
('huile', 'verre', 'lampe à huile'),
('lampe', 'lave', 'lampe à lave'),
('lumière', 'outil', 'lampe de poche'),
('ampoule', 'métal', 'lampe'),
('feu', 'pistolet', 'lance-flammes'),
('animal sauvage', 'carotte', 'lapin'),
('cochon', 'feu', 'lard'),
('cheval', 'corde', 'lasso'),
('corde', 'vache', 'lasso'),
('feu', 'terre', 'lave'),
('docteur', 'tardis', 'le docteur'),
('champ', 'fruit', 'légume'),
('crayon (mine de plomb)', 'papier', 'lettre'),
('marais', 'œuf', 'lézard'),
('arc en ciel', 'cheval', 'licorne'),
('arc en ciel', 'vie', 'licorne'),
('cheval', 'double arc en ciel!', 'licorne'),
('double arc en ciel!', 'vie', 'licorne'),
('mur', 'plante', 'lierre'),
('eau', 'fruit', 'limonade'),
('animal sauvage', 'chat', 'lion'),
('livre', 'recette', 'livre de recettes'),
('recette', 'recette', 'livre de recettes'),
('bois', 'papier', 'livre'),
('histoire', 'papier', 'livre'),
('humain', 'loup-garou', 'loup-garou'),
('humain', 'loup', 'loup-garou'),
('animal sauvage', 'chien', 'loup'),
('animal sauvage', 'Lune', 'loup'),
('chien', 'forêt', 'loup'),
('ampoule', 'électricité', 'lumière'),
('électricité', 'lampe de poche', 'lumière'),
('ciel', 'fromage', 'Lune'),
('ciel', 'pierre', 'Lune'),
('eau', 'lunettes', 'lunettes de natation'),
('explosion', 'lunettes', 'lunettes de protection'),
('ingénieur', 'lunettes', 'lunettes de protection'),
('lunettes', 'outil', 'lunettes de protection'),
('lunettes', 'neige', 'lunettes de ski'),
('lunettes', 'plage', 'lunettes de soleil'),
('lunettes', 'soleil', 'lunettes de soleil'),
('métal', 'verre', 'lunettes'),
('verre', 'verre', 'lunettes'),
('aiguille', 'électricité', 'machine à coudre'),
('aiguille', 'robot', 'machine à coudre'),
('énergie', 'humain', 'magicien'),
('bonhomme de pain d''épices', 'maison', 'maison en pain d''épices'),
('maison', 'pâte', 'maison en pain d''épices'),
('bois', 'humain', 'maison'),
('brique', 'humain', 'maison'),
('brique', 'outil', 'maison'),
('mur', 'mur', 'maison'),
('bateau à voile', 'maladie', 'mal de mer'),
('bateau', 'maladie', 'mal de mer'),
('maladie', 'mer', 'mal de mer'),
('maladie', 'navire à vapeur', 'mal de mer'),
('maladie', 'océan', 'mal de mer'),
('bactéries', 'humain', 'maladie'),
('humain', 'maladie', 'maladie'),
('humain', 'pluie', 'maladie'),
('boue', 'herbe-grass', 'marais'),
('boue', 'plante', 'marais'),
('Lune', 'mer', 'marée'),
('Lune', 'océan', 'marée'),
('bateau à voile', 'humain', 'marin'),
('bateau', 'humain', 'marin'),
('planète', 'rouille', 'Mars'),
('bois', 'métal', 'marteau'),
('huile', 'œuf', 'mayonnaise'),
('humain', 'serpent', 'méduse'),
('eau', 'eau', 'mer'),
('feu', 'pierre', 'métal'),
('atmosphère', 'météorite', 'météore'),
('ciel', 'météorite', 'météore'),
('espace', 'pierre', 'météorite'),
('bactéries', 'lunettes', 'microscope'),
('bactéries', 'verre', 'microscope'),
('abeille', 'fleur', 'miel'),
('abeille', 'ruche', 'miel'),
('crème glacée', 'lait', 'milk-shake'),
('espace', 'lait', 'Milky Way'),
('humain', 'vache', 'minotaure'),
('horloge', 'œuf', 'minuteur'),
('montre', 'œuf', 'minuteur'),
('métal', 'verre', 'miroir'),
('électricité', 'lame', 'mixeur'),
('lame', 'verre', 'mixeur'),
('pain', 'temps', 'moisissure'),
('cadavre', 'pyramide', 'momie'),
('château', 'humain', 'monarque'),
('couronne', 'humain', 'monarque'),
('excalibur', 'humain', 'monarque'),
('terre', 'tremblement de terre', 'montagne'),
('chariot', 'montagne', 'montagnes russes'),
('montagne', 'train', 'montagnes russes'),
('horloge', 'humain', 'montre'),
('chaudière', 'outil', 'moteur à vapeur'),
('chaudière', 'roue', 'moteur à vapeur'),
('acier', 'vélo', 'moto'),
('énergie', 'vélo', 'moto'),
('moto', 'neige', 'motoneige'),
('neige', 'voiture', 'motoneige'),
('mer', 'oiseau', 'mouette'),
('océan', 'oiseau', 'mouette'),
('oiseau', 'plage', 'mouette'),
('maison', 'vent', 'moulin à vent'),
('roue', 'vent', 'moulin à vent'),
('chocolat', 'noix de coco', 'Mounds'),
('algues', 'pierre', 'mousse'),
('pierre', 'plante', 'mousse'),
('bétail', 'nuage', 'mouton'),
('brique', 'brique', 'mur'),
('flûte', 'humain', 'musique'),
('humain', 'son', 'musique'),
('humain', 'lunettes de natation', 'nageur'),
('eau', 'pipe', 'narguilé'),
('eau', 'licorne', 'narval'),
('licorne', 'mer', 'narval'),
('licorne', 'océan', 'narval'),
('bateau', 'moteur à vapeur', 'navire à vapeur'),
('eau', 'moteur à vapeur', 'navire à vapeur'),
('dioxyde de carbone', 'froid', 'neige carbonique'),
('dioxyde de carbone', 'glace', 'neige carbonique'),
('froid', 'pluie', 'neige'),
('froid', 'vapeur', 'neige'),
('étang', 'fleur', 'nénuphar'),
('humain', 'lunettes', 'nerd'),
('nerd', 'sucre', 'Nerds'),
('histoire', 'lac', 'Nessie'),
('chien', 'maison', 'niche'),
('maison', 'oiseau', 'nichoir'),
('arbre', 'oiseau', 'nid'),
('foin', 'œuf', 'nid'),
('foin', 'oiseau', 'nid'),
('humain', 'shuriken', 'ninja'),
('fruit', 'palmier', 'noix de coco'),
('arbre', 'écureuil', 'noix'),
('air', 'vapeur', 'nuage'),
('ciel', 'Lune', 'nuit'),
('jour', 'temps', 'nuit'),
('Lune', 'temps', 'nuit'),
('arbre', 'désert', 'oasis'),
('désert', 'eau', 'oasis'),
('désert', 'palmier', 'oasis'),
('eau', 'lave', 'obsidienne'),
('eau', 'mer', 'océan'),
('mer', 'mer', 'océan'),
('pierre', 'vie', 'œuf'),
('lézard', 'lézard', 'œuf'),
('oiseau', 'oiseau', 'œuf'),
('tortue', 'tortue', 'œuf'),
('eau', 'œuf', 'œufs de poisson'),
('étang', 'œuf', 'œufs de poisson'),
('mer', 'œuf', 'œufs de poisson'),
('océan', 'œuf', 'œufs de poisson'),
('poisson', 'poisson', 'œufs de poisson'),
('air', 'œuf', 'oiseau'),
('air', 'vie', 'oiseau'),
('ciel', 'œuf', 'oiseau'),
('ciel', 'vie', 'oiseau'),
('feu', 'œuf', 'omelette'),
('arc en ciel', 'métal', 'or'),
('métal', 'soleil', 'or'),
('électricité', 'nerd', 'ordinateur'),
('fil électrique', 'nerd', 'ordinateur'),
('nerd', 'outil', 'ordinateur'),
('coton', 'tissu', 'oreiller'),
('oiseau', 'papier', 'origami'),
('canard', 'castor', 'ornithorynque'),
('cadavre', 'temps', 'os'),
('énergie', 'vent', 'ouragan'),
('humain', 'métal', 'outil'),
('avion', 'extraterrestre', 'ovni'),
('extraterrestre', 'fusée', 'ovni'),
('dioxyde de carbone', 'plante', 'oxygène'),
('plante', 'soleil', 'oxygène'),
('électricité', 'oxygène', 'ozone'),
('oxygène', 'oxygène', 'ozone'),
('acier', 'laine', 'paille de fer'),
('fil électrique', 'laine', 'paille de fer'),
('banane', 'pain', 'pain à la banane'),
('feu', 'pâte', 'pain'),
('arbre', 'île', 'palmier'),
('arbre', 'plage', 'palmier'),
('arc en ciel', 'oiseau', 'paon'),
('cadeau', 'papier', 'papier d''emballage'),
('papier', 'sable', 'papier de verre'),
('bois', 'pression', 'papier'),
('Lune', 'papillon', 'papillon de nuit'),
('nuit', 'papillon', 'papillon de nuit'),
('animal sauvage', 'fleur', 'papillon'),
('parapluie', 'pilote', 'parachute'),
('pilote', 'tissu', 'parachute'),
('outil', 'pluie', 'parapluie'),
('pluie', 'tissu', 'parapluie'),
('animal sauvage', 'temps', 'paresseux'),
('alcool', 'fleur', 'parfum'),
('alcool', 'rose', 'parfum'),
('eau', 'fleur', 'parfum'),
('eau', 'rose', 'parfum'),
('fleur', 'vapeur', 'parfum'),
('rose', 'vapeur', 'parfum'),
('musique', 'papier', 'partition'),
('gâteau', 'pâte', 'pâte à biscuits'),
('farine', 'lait', 'pâte à gâteau'),
('eau', 'farine', 'pâte'),
('fromage', 'pâtes', 'pâtes au fromage'),
('farine', 'œuf', 'pâtes'),
('canne à pêche', 'humain', 'pêcheur'),
('poulet', 'sucre', 'Peeps'),
('cheval', 'ciel', 'pégase'),
('cheval', 'oiseau', 'pégase'),
('licorne', 'oiseau', 'pégase'),
('arc en ciel', 'eau', 'peinture'),
('crayon (mine de plomb)', 'eau', 'peinture'),
('docteur', 'moisissure', 'pénicilline'),
('arbre de noël', 'humain', 'Père Noël'),
('oiseau', 'pirate', 'perroquet'),
('fossile', 'pression', 'pétrole'),
('fossile', 'temps', 'pétrole'),
('lumière', 'maison', 'phare'),
('lumière', 'mer', 'phare'),
('lumière', 'océan', 'phare'),
('lumière', 'plage', 'phare'),
('feu', 'oiseau', 'phénix'),
('chien', 'mer', 'phoque'),
('bois', 'fromage', 'piège à souris'),
('fromage', 'métal', 'piège à souris'),
('pierre', 'tombe', 'pierre tombale'),
('air', 'lave', 'pierre'),
('lettre', 'oiseau', 'pigeon'),
('oiseau', 'statue', 'pigeon'),
('oiseau', 'ville', 'pigeon'),
('avion', 'humain', 'pilote'),
('humain', 'hydravion', 'pilote'),
('animal sauvage', 'glace', 'pingouin'),
('glace', 'oiseau', 'pingouin'),
('neige', 'oiseau', 'pingouin'),
('bois', 'vie', 'pinocchio'),
('bois', 'tabac', 'pipe'),
('herbe-grass', 'sandwich', 'pique-nique'),
('plage', 'sandwich', 'pique-nique'),
('poisson', 'sang', 'piranha'),
('bateau pirate', 'marin', 'pirate'),
('épée', 'marin', 'pirate'),
('eau', 'pistolet', 'pistolet à eau'),
('balle', 'métal', 'pistolet'),
('bois', 'oiseau', 'pivert'),
('fromage', 'pâte', 'pizza'),
('eau', 'sable', 'plage'),
('mer', 'sable', 'plage'),
('océan', 'sable', 'plage'),
('ingénieur', 'papier', 'plan'),
('eau', 'vie', 'plancton'),
('mer', 'vie', 'plancton'),
('océan', 'vie', 'plancton'),
('espace', 'terre', 'planète'),
('pluie', 'terre', 'plante'),
('fumée', 'pluie', 'pluie acide'),
('pluie', 'smog', 'pluie acide'),
('air', 'eau', 'pluie'),
('eau', 'nuage', 'pluie'),
('frites', 'poisson', 'poisson-frites'),
('ciel', 'poisson', 'poisson volant'),
('oiseau', 'poisson', 'poisson volant'),
('œufs de poisson', 'temps', 'poisson'),
('écureuil', 'ordinateur', 'Pokki'),
('camion de pompier', 'humain', 'pompier'),
('feu', 'humain', 'pompier'),
('acier', 'rivière', 'pont'),
('bois', 'rivière', 'pont'),
('métal', 'rivière', 'pont'),
('explosion', 'pierre', 'Pop Rocks'),
('argent', 'cuir', 'portefeuille'),
('argile', 'feu', 'poterie'),
('argile', 'outil', 'poterie'),
('argile', 'roue', 'poterie'),
('feu', 'poussière', 'poudre à canon'),
('bétail', 'œuf', 'poulet'),
('bétail', 'oiseau', 'poulet'),
('fermier', 'oiseau', 'poulet'),
('air', 'terre', 'poussière'),
('jour', 'vampire', 'poussière'),
('soleil', 'vampire', 'poussière'),
('air', 'air', 'pression'),
('terre', 'terre', 'pression'),
('arc en ciel', 'verre', 'prisme'),
('air', 'dinosaure', 'Ptérodactyle'),
('dinosaure', 'oiseau', 'Ptérodactyle'),
('humain', 'laine', 'pull'),
('laine', 'outil', 'pull'),
('désert', 'pierre', 'pyramide'),
('désert', 'tombe', 'pyramide'),
('animal sauvage', 'bateau à voile', 'rat'),
('animal sauvage', 'bateau pirate', 'rat'),
('chien', 'glace', 'rauque'),
('chien', 'neige', 'rauque'),
('lumière', 'os', 'rayon x'),
('lumière', 'squelette', 'rayon x'),
('boulanger', 'papier', 'recette'),
('farine', 'papier', 'recette'),
('fil électrique', 'sucre', 'Red Vines'),
('bois', 'crayon (mine de plomb)', 'règle'),
('animal sauvage', 'poulet', 'renard'),
('animal sauvage', 'Père Noël', 'renne'),
('bétail', 'Père Noël', 'renne'),
('animal sauvage', 'mer', 'requin'),
('animal sauvage', 'océan', 'requin'),
('mer', 'sang', 'requin'),
('océan', 'sang', 'requin'),
('horloge', 'son', 'réveil'),
('diamant', 'sucre', 'Ring Pop'),
('eau', 'montagne', 'rivière'),
('montagne', 'pluie', 'rivière'),
('acier', 'vie', 'robot'),
('armure', 'vie', 'robot'),
('métal', 'vie', 'robot'),
('aspirateur', 'robot', 'roomba'),
('amour', 'fleur', 'rose'),
('amour', 'plante', 'rose'),
('brouillard', 'herbe-grass', 'rosée'),
('eau', 'herbe-grass', 'rosée'),
('eau', 'roue', 'roue à aubes'),
('rivière', 'roue', 'roue à aubes'),
('bois', 'outil', 'roue'),
('acier', 'air', 'rouille'),
('acier', 'oxygène', 'rouille'),
('air', 'métal', 'rouille'),
('métal', 'oxygène', 'rouille'),
('abeille', 'arbre', 'ruche'),
('abeille', 'maison', 'ruche'),
('château', 'temps', 'ruines'),
('maison', 'temps', 'ruines'),
('air', 'pierre', 'sable'),
('pierre', 'vent', 'sable'),
('marais', 'sable', 'sables mouvants'),
('sable', 'verre', 'sablier'),
('électricité', 'épée', 'sabre laser'),
('énergie', 'épée', 'sabre laser'),
('épée', 'lumière', 'sabre laser'),
('fromage', 'pain', 'sandwich'),
('jambon', 'pain', 'sandwich'),
('lard', 'pain', 'sandwich'),
('humain', 'lame', 'sang'),
('animal sauvage', 'cochon', 'sanglier'),
('cochon', 'forêt', 'sanglier'),
('anneau', 'planète', 'saturne'),
('cendre', 'huile', 'savon'),
('docteur', 'lame', 'scalpel'),
('hôpital', 'lame', 'scalpel'),
('animal sauvage', 'dune', 'scorpion'),
('animal sauvage', 'sable', 'scorpion'),
('feu', 'mer', 'sel'),
('feu', 'océan', 'sel'),
('mer', 'soleil', 'sel'),
('océan', 'soleil', 'sel'),
('cheval', 'cuir', 'selle'),
('animal sauvage', 'fil électrique', 'serpent'),
('plante', 'verre', 'serre'),
('fenêtre', 'fenêtre', 'serre'),
('étoile', 'lame', 'shuriken'),
('feu de camp', 'tissu', 'signal de fumée'),
('fumée', 'tissu', 'signal de fumée'),
('animal sauvage', 'arbre', 'singe'),
('humain', 'poisson', 'sirène'),
('roue', 'snowboard', 'skateboard'),
('arc en ciel', 'sucre', 'Skittles'),
('brouillard', 'fumée', 'smog'),
('brouillard', 'ville', 'smog'),
('fruit', 'mixeur', 'smoothie'),
('bois', 'neige', 'snowboard'),
('neige', 'surfeur', 'snowboard'),
('dioxyde de carbone', 'eau', 'soda'),
('dioxyde de carbone', 'jus', 'soda'),
('ciel', 'feu', 'soleil'),
('air', 'vague', 'son'),
('balai', 'humain', 'sorcière'),
('balai', 'magicien', 'sorcière'),
('eau', 'poulet', 'soupe de poulet'),
('ordinateur', 'souris', 'souris d''ordinateur'),
('animal sauvage', 'fromage', 'souris'),
('fil', 'pâtes', 'spaghetti'),
('humain', 'lion', 'sphinx'),
('cadavre', 'temps', 'squelette'),
('os', 'os', 'squelette'),
('fruit', 'fusée', 'Starburst'),
('espace', 'maison', 'station spatiale'),
('humain', 'méduse', 'statue'),
('outil', 'pierre', 'statue'),
('bbq', 'viande', 'steak'),
('feu', 'vache', 'steak'),
('docteur', 'outil', 'stéthoscope'),
('froid', 'jus', 'sucette glacée'),
('glace', 'jus', 'sucette glacée'),
('énergie', 'fruit', 'sucre'),
('énergie', 'jus', 'sucre'),
('feu', 'jus', 'sucre'),
('étoile', 'explosion', 'super nova'),
('humain', 'vague', 'surfeur'),
('algue', 'caviar', 'sushi'),
('algue', 'poisson', 'sushi'),
('poisson', 'sucre', 'Swedish Fish'),
('amour', 'sucre', 'Sweethearts'),
('planète', 'soleil', 'système solaire'),
('feu', 'plante', 'tabac'),
('crayon (mine de plomb)', 'lame', 'taille-crayon'),
('bois', 'cuir', 'tambour'),
('armure', 'voiture', 'tank'),
('pistolet', 'voiture', 'tank'),
('espace', 'temps', 'tardis'),
('fruit', 'pâte', 'tarte'),
('électricité', 'pistolet', 'taser'),
('animal sauvage', 'armure', 'tatou'),
('ciel', 'verre', 'télescope'),
('espace', 'verre', 'télescope'),
('étoile', 'verre', 'télescope'),
('énergie', 'sable', 'tempête de sable'),
('ouragan', 'sable', 'tempête de sable'),
('sable', 'tempête', 'tempête de sable'),
('électricité', 'nuage', 'tempête'),
('énergie', 'nuage', 'tempête'),
('sable', 'verre', 'temps'),
('bois', 'tissu', 'tente'),
('maison', 'tissu', 'tente'),
('froid', 'thé', 'thé glacé'),
('glace', 'thé', 'thé glacé'),
('eau', 'feuille', 'thé'),
('argent', 'cochon', 'tirelire'),
('cochon', 'poterie', 'tirelire'),
('fil', 'outil', 'tissu'),
('iceberg', 'navire à vapeur', 'titanic'),
('feu', 'pain', 'toast'),
('feu', 'sandwich', 'toast'),
('araignée', 'fil', 'toile'),
('cadavre', 'terre', 'tombe'),
('cercueil', 'terre', 'tombe'),
('électricité', 'faux', 'tondeuse à gazon'),
('herbe-grass', 'outil', 'tondeuse à gazon'),
('ninja', 'tortue', 'Tortue Ninja'),
('œuf', 'sable', 'tortue'),
('arc en ciel', 'oiseau', 'toucan'),
('fleur', 'soleil', 'tournesol'),
('plante', 'soleil', 'tournesol'),
('champ', 'voiture', 'tracteur'),
('fermier', 'voiture', 'tracteur'),
('acier', 'moteur à vapeur', 'train'),
('métal', 'moteur à vapeur', 'train'),
('moteur à vapeur', 'roue', 'train'),
('moteur à vapeur', 'wagon', 'train'),
('chariot', 'neige', 'traîneau'),
('neige', 'wagon', 'traîneau'),
('énergie', 'terre', 'tremblement de terre'),
('terre', 'vague', 'tremblement de terre'),
('carte au trésor', 'pirate', 'trésor'),
('électricité', 'hache', 'tronçonneuse'),
('étoile', 'pression', 'trou noir'),
('mer', 'tremblement de terre', 'tsunami'),
('océan', 'tremblement de terre', 'tsunami'),
('ingénieur', 'montagne', 'tunnel'),
('Caramelo', 'gâteau', 'Twix'),
('dinosaure', 'viande', 'tyrannosaurus rex'),
('anneau', 'volcan', 'une bague'),
('bétail', 'herbe-grass', 'vache'),
('mer', 'vent', 'vague'),
('océan', 'vent', 'vague'),
('astronaute', 'avion', 'vaisseau spatial'),
('humain', 'sang', 'vampire'),
('humain', 'vampire', 'vampire'),
('eau', 'énergie', 'vapeur'),
('eau', 'feu', 'vapeur'),
('fleur', 'poterie', 'vase'),
('plante', 'poterie', 'vase'),
('cadavre', 'oiseau', 'vautour'),
('roue', 'roue', 'vélo'),
('air', 'énergie', 'vent'),
('air', 'pression', 'vent'),
('arbre fruitier', 'champ', 'verger'),
('arbre fruitier', 'arbre fruitier', 'verger'),
('confettis', 'sucre', 'vermicelles'),
('électricité', 'sable', 'verre'),
('feu', 'sable', 'verre'),
('sel', 'viande', 'viande séchée'),
('soleil', 'viande', 'viande séchée'),
('bétail', 'boucher', 'viande'),
('bétail', 'lame', 'viande'),
('boucher', 'cochon', 'viande'),
('boucher', 'vache', 'viande'),
('cochon', 'outil', 'viande'),
('outil', 'vache', 'viande'),
('amour', 'temps', 'vie'),
('énergie', 'marais', 'vie'),
('maison', 'maison', 'village'),
('gratte-ciel', 'gratte-ciel', 'ville'),
('village', 'village', 'ville'),
('alcool', 'fruit', 'vin'),
('air', 'vin', 'vinaigre'),
('oxygène', 'vin', 'vinaigre'),
('temps', 'vin', 'vinaigre'),
('électricité', 'voiture', 'voiture électrique'),
('métal', 'roue', 'voiture'),
('feu', 'montagne', 'volcan'),
('lave', 'montagne', 'volcan'),
('lave', 'terre', 'volcan'),
('chariot', 'cheval', 'wagon'),
('ingénieur', 'sucre', 'Willy Wonka'),
('montagne', 'vache', 'yack'),
('bactéries', 'lait', 'yaourt'),
('chaîne de montagnes', 'histoire', 'yéti'),
('histoire', 'montagne', 'yéti'),
('Jedi', 'marais', 'Yoda'),
('froid', 'yaourt', 'yogourt glacé'),
('glace', 'yaourt', 'yogourt glacé'),
('cadavre', 'vie', 'zombie'),
('humain', 'zombie', 'zombie');

-- Now insert only the recipes where all 3 elements exist
INSERT INTO recipes (ingredient1_id, ingredient2_id, result_id)
SELECT 
  e1.element_id,
  e2.element_id,
  e3.element_id
FROM temp_recipes tr
INNER JOIN elements e1 ON e1.name = tr.ingredient1
INNER JOIN elements e2 ON e2.name = tr.ingredient2
INNER JOIN elements e3 ON e3.name = tr.result
ON CONFLICT DO NOTHING;

-- Show statistics
SELECT 
  (SELECT COUNT(*) FROM temp_recipes) as total_recipes_attempted,
  (SELECT COUNT(*) FROM recipes) as recipes_inserted,
  (SELECT COUNT(*) FROM temp_recipes) - (SELECT COUNT(*) FROM recipes) as recipes_skipped;

-- Cleanup
DROP TABLE temp_recipes;
