require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '16.0'
use_frameworks!

target 'App' do
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
